### ISSUE TITLE
GPP Carousel Bug

### ISSUE THREAD

**Issue by owendodd** [artsy/force#100]
in safari w/ one item in the carousel

cc @garrengotthardt 

![screen shot 2016-08-29 at 5 09 15 pm](https://cloud.githubusercontent.com/assets/3196536/18067630/9b148c08-6e0b-11e6-9455-2280facb4f16.png)

**Comment by garrengotthardt** [comment]
thanks @owendodd ! i think luckily this is just an artsy admin only issue (but cc @starsirius to confirm) - that fair booth its pulling in info for is an upcoming booth for which no works have been added and no cover image exists so its not published but for artsy admins the carousel is still trying to pull in the unpublished booth
