### ISSUE TITLE
Isolate event handling code from event triggering code

### ISSUE THREAD

**Issue by acjay** [artsy/force#1032]
In https://github.com/artsy/force/pull/1030, we had a critical process fail due to a small error in non-critical analytics code that ran on an event handler. We should consider isolating non-critical code on its own event loop pass using `setTimeout(/* ... */, 0)`, if it doesn't _need_ to run synchronously. (If it does, that's a whole other discussion :).)

Of course, this would have to be enforced by convention.

**Comment by damassi** [comment]
How does this look in terms of refactoring existing code within a (typically) unsafe event-based environment such as Backbone? How would one define critical vs non-critical? Like, "we're about to submit a bid, lets wrap the action to be extra safe"? Could you maybe provide an example?

**Comment by acjay** [comment]
So, it's tough to say. In a perfect world, I'd say all event listeners should be delayed until next tick. In the real world, it's possible this could break things, if we have places where code that follows a `trigger` call depends on side effects from an event handler. This is a dangerous pattern, but it's totally possible such dependencies might exist.

So given that we probably can't make a sweeping change to `trigger`'s semantics, I'm not sure I have a black-and-white notion in mind of what divides critical and non-critical code. Aside from this bug, probably anywhere else we need to make a marketing after a user action would count as non-critical. Not to say analytics aren't important, but we can't have marketing or analytics code derailing the UX of a monetary transaction. I think we'll realistically have to migrate things on a case-by-case basis. Which unfortunately means we'll be playing whack-a-mole. Not sure I have a better answer, but maybe someone does :D

**Comment by acjay** [comment]
Although, maybe with #1033, we could do something drastic, like modifying `trigger`/`on` (via mixin or whatever) to work on next tick, knowing that any emergent errors would be surfaced.
