### ISSUE TITLE
Client-side error aggregation

### ISSUE THREAD

**Issue by acjay** [artsy/force#1033]
The crash in https://github.com/artsy/force/pull/1030 is the result of [a 2-month old code change](https://github.com/artsy/microgravity-deprecated/blame/master/analytics/criteo.js#L31) (no disrespect intended by the Git blame), but we only detected it in ad hoc testing today. This particular issue could be prevented by #1031 and #1032, but other issues may not be so easily avoided. We can't regression test all our features all the time, so the next best thing is to make sure we at least _know_ when something breaks in production.

Client-side error reporting would probably be really noisy at first, but it would probably surface many existing production issues and regressions. We could filter out known issues from alerts as they are triaged, and eventually get to the point where we're only seeing alerts for new issues.

**Comment by damassi** [comment]
I've used [Raven.js](https://github.com/getsentry/raven-js) with [Sentry](https://sentry.io) quite effectively in the past -- @broskoski, thoughts? @sweir27 mentioned that you've done some research into this in the past.

**Comment by alloy** [comment]
Pretty sure @broskoski has been experimenting with adding an error reporting service, can’t recall which service it was from the top of my head.

**Comment by damassi** [comment]
Per https://artsy.slack.com/archives/C04DU9H0L/p1491954510204726, it looks like we now have an Artsy https://rollbar.com/ account. Anyone have any thoughts on taking it for a trial spin in Force?

**Comment by alloy** [comment]
@izakp was mentioning wanting to try out Sentry instead of NewRelic, at least for the server-side. Can we use 1 solutions for all?

**Comment by alloy** [comment]
After some more thought and experience thus far (from using NewRelic in Force), I’ve come up with the following list of requirements from such a service:

* Needs to be able to accept errors from server and client side JS.
* Needs to be able to symbolicate stack traces _on the service_ end. Symbolicating stack traces requires a bunch of memory, something we have to do right now for NewRelic, but I want to offload that completely from the server.

**Comment by alloy** [comment]
Dope, looks like rollbar supports [symbolication on their end](https://rollbar.com/docs/source-maps/), so that gets my thumbs up 👍 We’ll just need to keep an eye on its memory usage (3).

For now I’ll keep chipping away on #1177 so we eventually have proper source maps for all our source.

**Comment by alloy** [comment]
Rollbar does appear to be solely for error reporting and no other performance insights. Any thoughts as to what we could use for that? /cc @izakp

**Comment by izakp** [comment]
@alloy Sentry also supports JS sourcemaps https://docs.sentry.io/clients/javascript/sourcemaps/ - I would like to use one solution for client / server and across our apps and since we are moving some Rails apps to use Sentry rather than New Relic (I pushed back against Honeybadger as yet another service for Ruby) I would like to do the same here unless there is a very necessary feature Rollbar has that Sentry doesn't.

**Comment by izakp** [comment]
In terms of performance insights, any app can publish metrics to our statsd server at velocity.artsy.net

**Comment by alloy** [comment]
@izakp Alas Sentry does not actually support source maps for server-side errors https://github.com/getsentry/sentry/issues/2632, only client-side.

**Comment by damassi** [comment]
Can confirm that client-side source-maps work nicely, however.

**Comment by alloy** [comment]
> In terms of performance insights, any app can publish metrics to our statsd server at velocity.artsy.net

Good point 👍

**Comment by alloy** [comment]
The one I was referring to earlier, about being added by @broskoski, is https://raygun.com and was added in #806. It’s been running for a bit now and has been collecting a bunch of errors. You can sign-in from the Heroku addons list. I haven’t much looked into its offerings yet.

It too _appears_ to support source-maps from other platforms https://raygun.com/docs/workflow/source-maps. It only mentions mobile platforms, but the principle of rewriting files to URLs should probably work for any platform, including Node.

**Comment by alloy** [comment]
@izakp @damassi Started taking part of that Sentry thread about Node source-maps support: https://github.com/getsentry/sentry/issues/2632. I too would like us to settle on 1 tool as much as possible.

**Comment by izakp** [comment]
@alloy great initiative! 👏

**Comment by joeyAghion** [comment]
It looks like we've partially implemented Sentry for this. Server-side errors are reporting but I haven't identified any client-side errors so I suspect there's further integration work. (But I also might be missing something.)

As @damassi mentions in https://github.com/artsy/force/pull/1255, we should also clean up the Raygun integration (which is itself pretty recent) if we're moving in this new direction.

**Comment by alloy** [comment]
FYI Currently sourcemaps will work due to us including the lib that enables sourcemap symbolication at runtime, but in the future I’d like Sentry to support symbolication so we don’t need to spend memory (and CPU) on that.
