### ISSUE TITLE
Related artworks, other works in this show, etc not displaying on artwork pages

### ISSUE THREAD

**Issue by madeleineb** [artsy/force#1040]
This work, for example, is genomed but is unattributed (has Cultural Maker):
![image](https://cloud.githubusercontent.com/assets/5949572/24059088/0980714c-0b24-11e7-902e-62066eb6ccf0.png)

It should display the related artworks section because it has genomic similarity results.

All genomed works without an artist also missing Related artworks section: (https://www.artsy.net/artwork/506b6464dae14300020012b0, https://www.artsy.net/artwork/547df8987261693f16181400)

**Comment by robertlenne** [comment]
Actually, I think all artworks are missing related results?

**Comment by madeleineb** [comment]
@robertlenne You're absolutely right, all artwork pages are missing all sections including related works, other works in this show, other works by the artist, etc.

**Comment by madeleineb** [comment]
@alloy wanted to make sure you see this 🔥  ^

**Comment by robertlenne** [comment]
Think Matt z fixed it.

**Comment by mzikherman** [comment]
Closed by https://github.com/artsy/force/pull/1045

**Comment by madeleineb** [comment]
🙌 🎉 🙌
