### ISSUE TITLE
No related artwork results

### ISSUE THREAD

**Issue by robertlenne** [artsy/force#1044]
Seems like there are no related artwork results on force or martsy (there are on eigen). Other works from auction works.

**Comment by mzikherman** [comment]
Closed by https://github.com/artsy/force/pull/1045

**Comment by madeleineb** [comment]
Is this fixed? I am still not seeing any related results any works, with artsy genomes or partner genomes.  Related Artists rail isn't populated either.
 
![screencapture-artsy-net-artwork-the-haas-brothers-meryl-sheep-beast-settee-1490113776235](https://cloud.githubusercontent.com/assets/5949572/24158371/84bb58a2-0e32-11e7-9923-1c15afaef427.png)
---------
![image](https://cloud.githubusercontent.com/assets/5949572/24158428/af162d2a-0e32-11e7-8efc-4f05970067b6.png)

**Comment by mzikherman** [comment]
@madeleineb this is fixed! Can you link to that artwork page?

It looks fine to me.... https://www.artsy.net/artwork/54527f2f7261694c1d3d0100

**Comment by madeleineb** [comment]
Weird... it's working for me now too, I checked a number of artwork pages but also https://www.artsy.net/artwork/the-haas-brothers-meryl-sheep-beast-settee. 🤔 well, glad it's fixed
