### ISSUE TITLE
[Collector Marketing] Background image cut-off during resizing of window

### ISSUE THREAD

**Issue by alloy** [artsy/force#1050]
![screen shot 2017-03-20 at 17 20 41](https://cloud.githubusercontent.com/assets/2320/24109709/c9292362-0d91-11e7-85ab-0a76c44a8837.png)

**Comment by briansw** [comment]
@yuki24 @xtina-starr this seems to be happening only in safari. I'm also noticing a horizontal scrollbar always present as well:

![screen shot 2017-03-20 at 12 29 30 pm](https://cloud.githubusercontent.com/assets/1022172/24110085/edf0a608-0d68-11e7-824a-027e7813b008.png)
