### ISSUE TITLE
Partner sitemaps don't respect default_profile_public and lead to a 404

### ISSUE THREAD

**Issue by dblock** [artsy/force#1051]
Lots of sitemap entries lead to a 404.

![screen shot 2017-03-20 at 1 06 35 pm](https://cloud.githubusercontent.com/assets/542335/24111825/18f657c6-0d6e-11e7-9c06-e72f2b4ba919.png)

**Comment by alloy** [comment]
Should this move to the cinder repo?

**Comment by dblock** [comment]
This was fixed in cinder.
