### ISSUE TITLE
Gallery /artists leads to a spinner

### ISSUE THREAD

**Issue by dblock** [artsy/force#1052]
https://www.artsy.net/galerie-escougnou-cetraro/artists redirects to https://www.artsy.net/galerie-escougnou-cetraro/overview which spins.

![screen shot 2017-03-20 at 1 08 24 pm](https://cloud.githubusercontent.com/assets/542335/24111925/649cc764-0d6e-11e7-8aaf-2c87501aa7df.png)

**Comment by gnilekaw** [comment]
This page appears to be working correctly again. Closing for now. Lmk if it should be reopened.

<img width="1275" alt="screen shot 2017-04-03 at 1 12 18 pm" src="https://cloud.githubusercontent.com/assets/7292475/24621372/3d3a07e8-186f-11e7-9307-9206e3fb5d97.png">
