### ISSUE TITLE
Favorite section of /personalize contains unpublished artworks

### ISSUE THREAD

**Issue by broskoski** [artsy/force#1069]
This section uses a featured set that contains artworks that have been unpublished (and therefore cannot actually be saved, which is the primary action taken during this stage of the personalize flow).

Set id: `53c554ec72616961ab9a2000`

**Comment by alloy** [comment]
* needs an example link
* we could alternatively filter out unpublished works on our end

**Comment by madeleineb** [comment]
Yeesh, looks like 12/39 are unpublished. Replacing with other works by the same artists wherever possible.

In terms of how to make sure that these stay published, picking works in institutional collections is more stable, they're much less likely to be unpublished. @tayapage6 , can you give some feedback on what you think about this? in terms of recommendations, saving a work doesn't link you in any particular way to the gallery or collection it's in, it just adds those genes to your user_genome.

**Comment by madeleineb** [comment]
Okay, this should be good to go. I've replaced all the unpublished works with similar works, either by the same artist or something close by a different artist. 

I also made sure these works all have full genomes to ensure we'll be getting the most bang for buck when users save them.

**Comment by alloy** [comment]
👍
