### ISSUE TITLE
Email artsy admin on primer onboarding completion

### ISSUE THREAD

**Issue by broskoski** [artsy/force#1071]
"Can Sarah (sarah.gottesman@artsymail.com) get an automated email notification when users complete onboarding? Right now, she would need to manually check the user profile to see if anything has been updated."

**Comment by sperle** [comment]
@cab yes we can do that if the onboarding email lives in sailthru. We can trigger a custom script that sends an email and I'm 80% sure that can be to whomever we want.  However, for the pilot of this project these emails will not live in sailthru so I think we have some time to figure it out...

**Comment by mzikherman** [comment]
Question- if there are only 10 users for this program...do we really need an automated email that one of those ten have completed onboarding? Can we just do it manually?

And if we do want to automate it, it does seem like an email living in Sailthru (being triggered) would be how we go about doing it, so I'm a bit confused what still needs to happen.

Was this PR sufficient? https://github.com/artsy/force/pull/1073 This is the one that sets those `artsy_primer` vars in ST. Couldn't that be the thing that triggers this notification to Sarah?

**Comment by sperle** [comment]
For this test, correct, we're not doing any automated emails since it's only 10 people and there wasn't sufficient notice to create/build them in time for launch and yes that PR is sufficient (the trigger to send the email is on my side, which I'm still working on). There was one outstanding issue with the format of the date (https://github.com/artsy/force-private/issues/5485) but it's non-urgent.

**Comment by mzikherman** [comment]
Ah got it, so besides the date thing we are good?

(I'll move that issue for you btw, you made it in our now deprecated closed source repo!).

**Comment by sperle** [comment]
oops!

**Comment by sperle** [comment]
Yes, otherwise we're good

**Comment by alloy** [comment]
Should be fixed by #1105

**Comment by broskoski** [comment]
Closing, @sperle confirmed this is working.
