### ISSUE TITLE
Password reset form fails to submit

### ISSUE THREAD

**Issue by alloy** [artsy/force#1109]
For some reason Force redirects from `https://www.artsy.net/reset_password?reset_password_token=SECRET` to `/reset_password` which removes the reset token and thus leads to the form being impossible to submit.

![screen shot 2017-03-25 at 09 29 19](https://cloud.githubusercontent.com/assets/2320/24320898/821846cc-113f-11e7-9956-bf8df5e14a4e.png)

**Comment by alloy** [comment]
Oh I see, the token is set on the session before the redirect (not sure why, though?), so that’s actually all working correctly. It is Gravity that is responding with a 400.

**Comment by alloy** [comment]
Hrmm. For some reason no reset password token got stored on my user account: `user.reset_password_token # => nil`. However, subsequently I tried the process two more times and in both those cases my account did get a token assigned and I could successfully update my password.

So there appears to be a bit of a heisenbug 🌔 

@joeyAghion @mzikherman And ideas as to what could lead to these results?

**Comment by alloy** [comment]
Looking at [this metric](https://github.com/artsy/gravity/blob/75702862bfab3a7e84e0615e10fb4fd222952f8c/app/api/v1/users_passwords_endpoint.rb#L32) doesn’t show a significant increase over the last few months, so at least it’s not massively failing.

**Comment by joeyAghion** [comment]
If you can repro this I'd love to poke around in the browser session. Gravity updates a timestamp, generates a token, and notifies Pulse [to send the email] when a password-reset request happens, so we should be able to verify if that's being traversed. If not, maybe a client-side error is getting swallowed?

Note that reset requests short-circuit if it's been less than 5 minutes since the last request. Could that have explained what you saw?

**Comment by dblock** [comment]
Indeed we don't let you ask for too many resets to avoid a brute force attack. Furthermore the token is removed from the URL to avoid keeping it in browser history or something like that.

**Comment by alloy** [comment]
This was on the first try after being reported in Slack, subsequent tries did work. I haven't been able to reproduce it since then, so going to close it for now and report back if I run into it again.

@dblock ah yeah, that redirect makes a ton of sense 👌
