### ISSUE TITLE
Fair sitemaps have broken links to fairs without a public profile

### ISSUE THREAD

**Issue by dblock** [artsy/force#1114]
For example, `viennacontemporary-2017` is a published Fair record in Gravity, but https://www.artsy.net/viennacontemporary-2017 doesn’t exist. This is because either fair doesn't have a profile or the profile is set to private.

**Comment by alloy** [comment]
Should this move to the cinder repo?

**Comment by xtina-starr** [comment]
@alloy it indeed belongs here. I have a PR open for it https://github.com/artsy/force/pull/1136
