### ISSUE TITLE
[Fair] Works link doesn’t work consistently

### ISSUE THREAD

**Issue by alloy** [artsy/force#1116]
* From a browser (e.g. Safari)
* With an iOS user-agent
* Loading the ‘Works’ link on https://www.artsy.net/miart-2017 leads to a 404

----

* From Eigen in staging
* Loading the ‘Works’ link on https://staging.artsy.net/miart-2017 leads to a 404

----

* From Eigen in production
* Loading the ‘Works’ link on https://www.artsy.net/miart-2017 loads a desktop version of the view

**Comment by gardnerae** [comment]
@alloy @xtina-starr seems as though it's now fixed. i played around with the href links in Waves for each of these modules and they now seem to work?? i mostly just verified that they were the same as on other fairs, like AIPAD.

**Comment by alloy** [comment]
@gardnerae Seems like you fixed it 👍 Do you know what the difference in links was?

**Comment by xtina-starr** [comment]
Yeah I just started looking into this and am having trouble reproducing @alloy @gardnerae
