### ISSUE TITLE
Memory profiling

### ISSUE THREAD

**Issue by izakp** [artsy/force#1118]
We need a way to profile memory usage.  Some options:

- Install https://www.npmjs.com/package/@newrelic/native-metrics
- Log heap into https://github.com/marcominetti/node-memwatch
- Occasionally take a snapshot and upload to S3 https://github.com/bnoordhuis/node-heapdump

**Comment by alloy** [comment]
I’m making a module to perform heap dumps when leaks are detected. Will PR soon.

**Comment by izakp** [comment]
Thanks @alloy - good we now have a means of introspection... we'll get you yet darn leaks!
