### ISSUE TITLE
Couple of weird things on gallery insights

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1134]
Weird line break / read dot on email sign up
![screen shot 2017-03-29 at 8 22 02 pm](https://cloud.githubusercontent.com/assets/3196536/24470008/b96481aa-14bd-11e7-9351-69313130bcb1.png)

Weirdness with share buttons
<img width="629" alt="screen shot 2017-03-29 at 8 23 56 pm" src="https://cloud.githubusercontent.com/assets/3196536/24470028/ca1dae5e-14bd-11e7-99d5-585fd7b26e76.png">

**Comment by eessex** [comment]
Got the line break -- what weirdness are you getting with the share buttons?  I have noticed recently that they are a bit buggy, but nothing that is specific to gallery insights. Maybe we should start a new issue for this, or add to this one: https://github.com/artsy/force/issues/58

**Comment by eessex** [comment]
Looks like Chrome changed their implementation of sticky: https://developers.google.com/web/updates/2016/12/position-sticky

I wonder if the weirdness is because the polyfill is no longer being used?  A comment on that article says it doesn't work if implemented via javascript.
