### ISSUE TITLE
Strip down error page to depend _only_ on the error object (minimal layout)

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force#1148]
We get these silly errors thrown like `Cannot read property 'CURRENT_USER' of undefined` or `asset is not a function` because the error page re-uses our main layout and errors that throw before those things are added to locals cause this noise.

**Comment by sweir27** [comment]
Just noting that I also receive this error locally when accessing other (non-error) pages in force, kind of spuriously. I'll keep an eye out for a pattern, but perhaps the problem is more widespread.
