### ISSUE TITLE
Artist Page carousel nav off

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#117]
Showing up on the top right instead of the middle. artsy.net/artists
![image](https://cloud.githubusercontent.com/assets/2236794/18208174/5eb83fd6-70fc-11e6-9be9-776f3e601fcc.png)

**Comment by xtina-starr** [comment]
This appears to be fixed. Closing the issue.

![screen shot 2016-09-09 at 11 46 44 am](https://cloud.githubusercontent.com/assets/5201004/18393406/38313d22-7683-11e6-8eb0-5d76165c4524.png)
