### ISSUE TITLE
Issues with Marketo landing pages

### ISSUE THREAD

**Issue by cfinsness** [artsy/force#1178]
Hi, not sure if this is the right place to place these issues, let me know if otherwise.

1. Modal - When you open this page, and scroll before the modal pops up, it could appear just gray 
http://pages.artsy.net/gallery-insights-alan-cristea-case-study.html

<img width="1343" alt="screen shot 2017-04-05 at 10 37 45 am" src="https://cloud.githubusercontent.com/assets/6314270/24710707/f2f72b2e-19eb-11e7-9ecb-2417caf78c7e.png">

Related marketo template is here - https://app-ab14.marketo.com/#LT1287B2ZN12
Related marketo lp edit - https://app-ab14.marketo.com/#LP2035B2

2. Responsiveness - when you drag this page into a different size you'll see that the elements get distorted http://insights.artsy.net/social-media-toolkit

<img width="494" alt="screen shot 2017-04-05 at 10 40 34 am" src="https://cloud.githubusercontent.com/assets/6314270/24710849/55aa4706-19ec-11e7-8c68-bec7a31ec1cc.png">

Related template - https://app-ab14.marketo.com/#LT1019B2ZN12
Related marketo lp edit - https://app-ab14.marketo.com/#LP1323B2

Please let me know if I can clarify anything! 

cc @katarinabatina

**Comment by alloy** [comment]
Issue moved to [artsy/collector-experience #226](https://github.com/artsy/collector-experience/issues/226) via [**ZenHub**](https://www.zenhub.com/)
