### ISSUE TITLE
Don't allow CR/LF in titles

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#1195]
Titles should be flat otherwise this breaks sitemaps and other things.

**Comment by dblock** [comment]
It doesn't (or shouldn't) break sitemaps. What other places does it break things?

**Comment by kanaabe** [comment]
Oops moving this to Positron. The issue is that the editor currently allows newlines to be entered in the title, but we don't render that on the frontend. 

Sorry I didn't realize it doesn't actually break sitemaps!
