### ISSUE TITLE
Exhibition history spacing around comma looks weird

### ISSUE THREAD

**Issue by dblock** [artsy/force#121]
https://www.artsy.net/artwork/valery-chtak-five-thousand-years-ago

<img width="727" alt="screen shot 2016-09-07 at 8 53 16 am" src="https://cloud.githubusercontent.com/assets/542335/18312611/9d599598-74d8-11e6-953d-c191fa13f6e6.png">

Should be stuck to 2013.

Chrome

**Comment by broskoski** [comment]
Happy birthday @dblock 🎆 🎂 🎁
