### ISSUE TITLE
Venice Biennale Landing Page Overview

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1237]
Landing page for the video series we are producing for the venice biennale. 

Some high level notes:
• Each video needs it own url, and should be loaded dynamically. 
• Hitting the base url should redirect to the first video
• Each video exists as a carousel that has two states _live_ and _preview_. 

• Live videos have a video file, a cover image, associated artist(s), a title and a description
• Preview videos have a cover image, and a title
• All UBS logos should link to them

Video Player
• Default state is a full screen image BG
• Play button also shows time (not totally necessary)
• Play button and side arrow hover states should both be solid white fill with black arrow / text
• On hitting play title, nav and image should fade out, while video + pause button in bottom left should fade out and video should fade in / autoplay.
• once video finishes it should fade to black and show 'Read more' (scrolls down page) 'Next video' (navigates right) + Share

Lower Priority:
• Venice Coverage footer rail (other editorial coverage)
• Text link feature
• Artist follow compontent
• Open in Youtube app button

Sketch file here: https://cl.ly/2p392c24251l

![header on an article copy 50](https://cloud.githubusercontent.com/assets/3196536/25052080/58dacbd8-2150-11e7-9e48-c9a44b0e9577.jpg)

**Comment by kanaabe** [comment]
@owendodd @eessex: Gonna get a checklist going again, I found it helpful last time for EOY! Feel free to use/not use. 

Analytics
- [ ] Video play
- [ ] Video dropoff time
- [ ] Clicked UBS
- [ ] Pageview

Page
- [ ] URL for each video
- [ ] Default to first video
- [ ] Live and Preview states
- [ ] Cover Overlay
- [ ] Completed Video Overlay
- [ ] Circle Navigation

Live State: Player & Streaming
- [ ] Pause button
- [ ] Scrubbing
- [ ] HLS vs MP4
- [ ] Unsupported Browser Warning
- [ ] User agent check for best video quality

Preview State
- [ ] Subscribe button

Meta Section
- [ ] About the Series
- [ ] Index
- [ ] Video Description
- [ ] Share

Lower Priority
- [ ] Venice Coverage footer rail (other editorial coverage)
- [ ] Text link feature
- [ ] Artist follow compontent
- [ ] Open in Youtube app button


@eessex

**Comment by kanaabe** [comment]
@owendodd Do we want to add audio controls and the View in Cardboard option somewhere too?

**Comment by owendodd** [comment]
@kanaabe good call. def makes sense to add. I'll adjust the player UI to accommodate.

**Comment by kanaabe** [comment]
@owendodd if possible, I'd like to put the View in Cardboard option somewhere at the top of the player:

![image](https://cloud.githubusercontent.com/assets/2236794/25197158/0975aad0-2511-11e7-920b-6fb932ba4328.png)

The long explanation: there are two parts to the player -- the controls overlay (which is hosted on Force), and the VR canvas iframe (which is hosted in an S3 bucket). The controls have our scrubber, play/pause button etc. However, the View in Cardboard button _has_ to be placed on the VR canvas side. Reasoning about whether we should open space on the bottom for this button (am i on desktop or mobile?) is going to get messy and I'd rather we just place it somewhere that the controls definitely won't overlap with. 

It's also starting to get a little crowded at the bottom on mobile with the button, scrub, vricon, audio, and cardboard all there. Lmk if that works for ya!

**Comment by owendodd** [comment]
![iphone 7 copy 15](https://cloud.githubusercontent.com/assets/3196536/25286806/b37ef722-26c7-11e7-8976-a45d82057a10.png)
![iphone 7 copy 19](https://cloud.githubusercontent.com/assets/3196536/25286808/b4d915bc-26c7-11e7-8db0-bee3b6be885e.png)

**Comment by owendodd** [comment]
@kanaabe How does this look? Desktop would be the same sans the cardboard icon.

**Comment by kanaabe** [comment]
👏  Sweet thank you!

What do you think about simplifying the volume to just Mute/Unmute? I usually just use the volume control on my phone/keyboard if I need to adjust. Facebook and NYT just does mute/unmute.

For more technical convincing, we have to hook into the VR View to adjust the video volume, and I think with a slider, it becomes heavier for the VR View to listen on slider-type events vs a simple button. It's definitely possible -- I'm just trying to keep the number of events going into the VR View to a minimum.

**Comment by owendodd** [comment]
@kanaabe yeah that's fine with me! 

Almost makes me wonder if we could just not include it at all. But its probably good to have something. What do you think?

**Comment by kanaabe** [comment]
I'll put it in for now and we can take it out if it feels too bulky on smaller phones. Not difficult to add the toggle at all.

**Comment by owendodd** [comment]
@kanaabe @eessex 

Here is the 360 guide modal. Sketch file [here](https://cl.ly/1D13140l2w46). I created this [article draft](https://writer.artsy.net/articles/5901d64b4682400017f0e3cb/edit) that it could pull from (wasn't sure if this should live as an Ed. article or somewhere else). 

![header on an article copy 56](https://cloud.githubusercontent.com/assets/3196536/25482293/747066c2-2b51-11e7-85ae-f862e1fd605b.jpg)

**Comment by owendodd** [comment]
Mobile QA: Seeing some funky alignment in two places:

![img_6505](https://cloud.githubusercontent.com/assets/3196536/25482361/bade3896-2b51-11e7-9944-5cbc6bd6364c.PNG)
![img_6506](https://cloud.githubusercontent.com/assets/3196536/25482362/baef1daa-2b51-11e7-97ea-a1f36fa65885.PNG)

**Comment by owendodd** [comment]
Slight updates to the player UI:

- Adds in the X to close out
- Adds in an info icon which would scroll you down the page ([svg here](https://cl.ly/0Y081I171602)). This icon would always be present
- Removes black opacified bg from 360 icon as it isn't clickable

![header on an article copy 49](https://cloud.githubusercontent.com/assets/3196536/25483342/a3874cce-2b55-11e7-8311-7d80d85ef4f7.jpg)
![header on an article copy 52](https://cloud.githubusercontent.com/assets/3196536/25483344/a38a0860-2b55-11e7-957c-da9f0890bf47.jpg)
![iphone 7 copy 15](https://cloud.githubusercontent.com/assets/3196536/25483343/a38884d6-2b55-11e7-84f5-d7d608b5759e.png)

**Comment by owendodd** [comment]
Alt Signup for people who are already logged in / signed up and for to replace the form after somebody signs up. 

![header on an article copy 51](https://cloud.githubusercontent.com/assets/3196536/25483442/255bcbda-2b56-11e7-95e9-685fdc5d8dd1.jpg)
![header on an article copy 57](https://cloud.githubusercontent.com/assets/3196536/25483441/255b25d6-2b56-11e7-9dc5-e7dc1f27a3e1.jpg)

**Comment by owendodd** [comment]
Not necessary for launch but wondering if we can make the info button scroll down the page rather than jump. @eessex

**Comment by halleyjohnson** [comment]
Big priorities I know about:
[ ] File isn't rendering in Cardboard view for some mobile browsers, file too big?

[ ] Facebook share image needs to be updated


Secondary priorities:

[ ] Parsely analytics should be added

[ ] Sailthru metadata should be added


Two small updates when we've taken a breath:

[ ] Update YouTube language to the following: 
For the most immersive 3D experience, watch in Google Cardboard via the YouTube app.

[ ] Markdown links don't seem to be rendering in the About the Series copy
![screen shot 2017-05-03 at 3 41 21 pm](https://cloud.githubusercontent.com/assets/10982707/25678227/fc0a197e-3016-11e7-9110-5cd2b6007c9f.png)
