### ISSUE TITLE
[Venice] Analytics

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#1305]
[Link to project](https://github.com/artsy/force/issues/1237)

- [x] Video play
- [x] Video dropoff time Q: what's the best way to track this? Right now we're tracking whenever someone exits the page entirely.
- [x] Video duration as a percentage
- [x] Clicked UBS
- [x] Pageview
- [x] Signup
- [x] Follow artist

We have track calls ready for each of these events and we just need the preferred wording for things like:
`context_type`
`impression_type`
`destination_path`

First video launches May 3. 
http://staging.artsy.net/venice-biennale for testing (log in as Admin)

cc @anipetrov @owendodd

**Comment by kanaabe** [comment]
Sorry we jumped the gun and there's a PR out there for this that takes care of all the cases above: https://github.com/artsy/force/pull/1306/files

We can do a follow up PR with updates to naming afterwards! (since the page isn't public yet, it won't affect any real data)

**Comment by anipetrov** [comment]
sounds good, thanks @kanaabe

**Comment by eessex** [comment]
looks like beforeUnload is giving us a dialog on close
![screen shot 2017-04-26 at 5 52 15 am](https://cloud.githubusercontent.com/assets/1497424/25428712/98295bc2-2a44-11e7-8b58-e9276226e6e7.png)

**Comment by kanaabe** [comment]
Oh whoops thought we took care of that but I must have changed something. Thanks for catching @eessex

**Comment by eessex** [comment]
Regarding tracking for video plays/duration, do we want to track which video they are watching?

**Comment by owendodd** [comment]
Yeah I think that would be good.

[A.]  Owen Dodd

       Designer

       Artsy <http://artsy.net/>

owen@artsy.net

+1 303 819 0844 <//+1%20303%20819%200844>

On April 27, 2017 at 12:48:30 PM, Eve Essex (notifications@github.com)
wrote:

Regarding tracking for video plays/duration, do we want to track which
video they are watching?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/artsy/force/issues/1305#issuecomment-297680019>, or mute
the thread

**Comment by mikehrom** [comment]
Hey! Took a look at this with Will -- just a few notes:

1. The "sign up for the newsletter" button submission should be instrumented so we know how many signups we get from this
2. The "read our 360 guide" link doesn't go anywhere yet, I assume that's known
3. We should instrument the social buttons
4. 
- The `Followed artist` event should have `context_type: venice_biennale_2017`, and should have an `entity_id`
 - The follow widget `Followed artist` event should have a `model_name` to be consistent with the other event, and should also have `context_type`
5. Minor, but we don't need `impression_type` on any of these events, it's redundant with the event name

Suggested naming:
For item 1, we already have a `Sign up for editorial email` event, so you could use
```js
analytics.track('Sign up for editorial email', { user_email: xxx, context_type: venice_biennale_2017' }
```
For item 3, maybe something like this
```js
analytics.track('Click social share', { service: 'twitter', context_type: 'venice_biennale_2017' } 
```

Also re: your questions - we think the way you're tracking video dropoff time is good as is.

**Comment by wrgoldstein** [comment]
Actually do we need video dropoff if we have time watched? a user who watched 3/4s but not the whole thing obviously dropped off.

**Comment by kanaabe** [comment]
Thanks @mikehrom and @wrgoldstein! #2 is known. The rest make sense to me. 

I invited you to a meeting tomorrow where we'll talk to Mark about dropoff and duration. The video will be posted on multiple platforms (Vimeo, Youtube, FB) and they all seem to have their own definitions of dropoff/duration, so we'll align on what to expect from the landing page. Hope either of you can make it!

**Comment by eessex** [comment]
Thank you @mikehrom and @wrgoldstein -- Regarding the artist follow button, it looks like the existing module uses 'context_page' rather than 'context_type', let me know if we should override.

For video events, we had discussed identifying individual videos in the events, does this make sense to you, and if so what naming should be used to identify?

**Comment by kanaabe** [comment]
Should we track a pageview each time someone rotates the carousel? The URL changes.

**Comment by kanaabe** [comment]
More events that may need naming details after meeting with @wrgoldstein &co: 

- [ ] 3 second
- [ ] 10 second
- [ ] Anything 360 video specific? (movement etc -- we may not be able to get this)
- [ ] View in Cardboard button

**Comment by kanaabe** [comment]
@wrgoldstein / @mikehrom would you guys mind checking that everything looks alright on staging? Everything _should_ be in now.

**Comment by mikehrom** [comment]
@wrgoldstein @kanaabe @eessex hi! following up on all the outstanding questions

- Use `context_type` instead of `context_page` to be consistent with existing force schema

- Re: carousel tracking, we went back and forth on this, but I figure if it can be easily tracked, we should track it. how about `next_page_in_carousel` and `previous_page_in_carousel`? 

- the naming details for video view duration (`video_seconds`) are fine as-is 

- Need to add video title:

```
analytics.track('Video play', { context_label: 'searching_for_venice', context_type: 'venice_biennale_2017' }

analytics.track('Video seconds', { context_label: 'searching_for_venice', context_type: 'venice_biennale_2017' }
```

**Comment by kanaabe** [comment]
@mikehrom 

@eessex  pointed out that `context_page` is used on Follow buttons across the site. If we changed that to `context_type` for this specific use, it would be inconsistent with the rest of the site. Do we still want that?

Minor but asking anyway: would it make a difference to you if we used `context_label: 'searching_for_venice'` vs `context_label: 'Searching for Venice'` (the title) or even `context_label: 'searching-for-venice'` (the url slug)?

**Comment by mikehrom** [comment]
@kanaabe on second thought, the page path (which we track) tells us the same information as the `context_page` so we don't even really need that or a `context_type` 

to the second question, using hyphens like the url slug works for us (i.e. `context_label: 'searching-for-venice'`)

**Comment by kanaabe** [comment]
@mikehrom excellent -- thanks for the quick answers and help! 💯  Will follow up once more when this last batch of analytics are on staging.

**Comment by kanaabe** [comment]
@mikehrom analytics are on staging

**Comment by mikehrom** [comment]
@kanaabe i'm seeing a `context_label` for the `Video seconds` and `Video duration` events but not for the `Video play` event
