### ISSUE TITLE
2015 Venice Redirect Banner

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1328]
This banner should live on the 2015 feature and the associated articles (if possible).

![header on an article copy 49](https://cloud.githubusercontent.com/assets/3196536/25529855/31d84036-2c24-11e7-8324-1188d7222bff.jpg)
![iphone 7 copy 13](https://cloud.githubusercontent.com/assets/3196536/25529854/31d8284e-2c24-11e7-898b-bc20a7ac4e61.png)

Sketch: https://cl.ly/2043040F3x2b

**Comment by eessex** [comment]
@owendodd, @mikehrom, @wrgoldstein -- do we want any analytics associated with this banner?

**Comment by owendodd** [comment]
yeah, # of clicks would be good to know. thanks eve!

**Comment by eessex** [comment]
@owendodd, @mikehrom, @wrgoldstein - do you want the source url or article id?  currently event is `Clicked Venice 2017 Banner link: context_type: 'venice_biennale_2017'`
Would we like this banner to appear on Venice articles from 2017 as well?
