### ISSUE TITLE
Auction page estimate filter breaks on click

### ISSUE THREAD

**Issue by erikdstock** [artsy/force#1341]
@devangt found this- Basically if you click on the estimate page filter at the top limit all artworks go away.

![pricefilterbug](https://cloud.githubusercontent.com/assets/9088720/25587738/48bbd8de-2e73-11e7-9d2a-7d2e4cda4c56.gif)

**Comment by sweir27** [comment]
I think this is actually a dup of https://github.com/artsy/force/issues/1242 (as force is currently in a rolled-back state).

**Comment by erikdstock** [comment]
Correct @sweir27 - closing.
