### ISSUE TITLE
home page reloads indefinitely under some circumstances

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#1351]
(Discussed here: https://artsy.slack.com/archives/C04DU9H0L/p1493736664756377)

A few of us have experienced an indefinitely-reloading home page with the Chrome inspector open and in mobile device mode. (Hopefully this is limited to visits with the inspector open.) I can't easily reproduce, but others encountered it as well. Based on the statistics posted in that conversation, I fear it's more widespread, and introduced around the end of March/beginning of April.

**Comment by robinwhittleton** [comment]
I’m seeing infinite reloads on artsy since I signed up a couple of weeks ago. Has made the service unusable on iOS Safari. Happy to help debug.
