### ISSUE TITLE
Client-side reaction-force import gets breaks when assets are compiled

### ISSUE THREAD

**Issue by broskoski** [artsy/force#1380]
To reproduce locally: 

![screenshot 2017-05-03 18 24 05](https://cloud.githubusercontent.com/assets/821469/25684314/9fbcff2a-302e-11e7-9fcb-7255072816ef.png)

- Open `desktop/assets/categories.coffee`
- Change `require('../apps/tag/client.coffee').init` to `require('../apps/tag/client.js').default.init`
- Run `yarn assets && NODE_ENV=x yarn start`
- Visit any tag page (i.e. http://localhost:5000/tag/glass )

**Comment by broskoski** [comment]
Seems logical that this is happening somewhere in browserify-ing / babelify-ing .  Upgrading `babel-core`, `babel-runtime`, `browserify`, and `babelify` yielded the same results after compilation. Specifically setting the presets `"es2015", "react", "stage-3"` in `scripts/assets.sh` also yielded the same results. Currently still investigating...

**Comment by alloy** [comment]
Ah I was wondering where the instructions were to reproduce, I hadn’t seen this ticket :)
