### ISSUE TITLE
Bylines incorrect for year round fair pages on mobile

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1389]
![image1_480](https://cloud.githubusercontent.com/assets/3196536/25743523/222004fa-3195-11e7-992e-f646d6c51caa.png)
![screen shot 2017-05-04 at 2 16 08 pm](https://cloud.githubusercontent.com/assets/3196536/25743524/223a1066-3195-11e7-8795-7576bd2a95ba.png)

**Comment by eessex** [comment]
@owendodd, what is the url you are using for the mobile view?  I'm seeing no authors listed for non-editorial pieces on the fair overview, while /dallas-art-fair-2017/articles gives a 500 on mobile.
![screen shot 2017-05-15 at 2 58 27 pm](https://cloud.githubusercontent.com/assets/1497424/26074250/0b7332b2-397f-11e7-821c-8a0b380d013d.png)

**Comment by owendodd** [comment]
Hmm, these screenshots were passed on to me by someone else. I’ll do a
little more idgging


[A.]  Owen Dodd

       Designer

       Artsy <http://artsy.net/>

owen@artsy.net

+1 303 819 0844


On May 15, 2017 at 8:59:54 PM, Eve Essex (notifications@github.com) wrote:

@owendodd <https://github.com/owendodd>, what is the url you are using for
the mobile view? I'm seeing no authors listed for non-editorial pieces on
the fair overview, while /dallas-art-fair-2017/articles gives a 500 on
mobile.
[image: screen shot 2017-05-15 at 2 58 27 pm]
<https://cloud.githubusercontent.com/assets/1497424/26074250/0b7332b2-397f-11e7-821c-8a0b380d013d.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/artsy/force/issues/1389#issuecomment-301571405>, or mute
the thread

**Comment by eessex** [comment]
@owendodd thanks i was able to find this on slack!
