### ISSUE TITLE
Sign_up_user_agents get overwritten by node

### ISSUE THREAD

**Issue by anipetrov** [artsy/force#1390]
When we implemented server events in November, we started overwriting the `sign_up_user_agent` associated with every non-eigen user in gravity. For a couple of months all of the force/mG users’ user agents looked like this: `node-superagent/1.8.5`. Craig PR-ed a fix at the end of January: https://github.com/artsy/artsy-passport/commit/bda9dc028334380317cb227466d27ed7bdc4b9df. 
However, we still see some user agents overwritten by node. In fact, going back in time we see this happening (to a much smaller extent) since march 2016. You can see user count breakdown by user agent here: https://artsy.looker.com/sql/rxjvvkfqhnkmjc

![image](https://cloud.githubusercontent.com/assets/8701687/25756797/161e0e76-3196-11e7-8d73-b8fee413ec6e.png)

`sign_up_user_agent` is a major way in which we track if a user has created an account on desktop, mobile, or eigen, so it is very important to get the proper user agent when possible. 

cc @craigspaeth

**Comment by tayapage6** [comment]
@anipetrov Is it possible to back-fix any of this data?

**Comment by anipetrov** [comment]
@tayapage6 I do not think we would be able to

**Comment by anipetrov** [comment]
thank you so much for taking a look and fixing this @craigspaeth! i will monitor!

**Comment by craigspaeth** [comment]
Np! Sorry I might have pre-emptively closed this—it's waiting to be deployed [in this](https://github.com/artsy/force/pull/1410) which should go out by EOD.

**Comment by anipetrov** [comment]
sounds good, i'll keep in mind!
