### ISSUE TITLE
all logged-in visits to /auction/:id/confirm-registration trigger confirmation message

### ISSUE THREAD

**Issue by erikdstock** [artsy/force#1422]
To reproduce:
-Be logged in
-But not registered for an auction
-on the auction page, append `/confirm-registration`
--> See the confirmation modal

Minor, but found while testing a registration-related ticket (https://github.com/artsy/force/pull/1417)

![image](https://cloud.githubusercontent.com/assets/9088720/26013532/e7141cba-3726-11e7-9e44-ecfc5e21b4f0.png)

**Comment by sweir27** [comment]
👍 this is probably minor as there aren't any paths to this page except after you successfully register from within the app, but the issue of the modal popping up when there is no paddle number happens even in normal usage and is pretty annoying. Ticketed here: https://github.com/artsy/auctions/issues/426 for reference in case the fix addresses both issues!
