### ISSUE TITLE
QA on article-related events

### ISSUE THREAD

**Issue by joelauerbach** [artsy/force#143]
Following up on https://github.com/artsy/force-private/issues/5375.
cc: @kanaabe @owendodd @anipetrov 

1) `Article impression [social]` fires when social widget is hidden under "Read more".

![screen recording 2016-09-13 at 12 02 pm](https://cloud.githubusercontent.com/assets/15615381/18482940/2c82bcfa-79b0-11e6-8cd5-57b2b4f82f65.gif)

2) `Article impression [related article]` doesn't fire for related articles.

![image 2016-09-13 at 12 07 10 pm](https://cloud.githubusercontent.com/assets/15615381/18482984/50350996-79b0-11e6-88bb-ca8ff46b2b75.png)

3) `Article impression [artist follow]` sometimes fires when artist follow button is hidden under "Read more".

![screen recording 2016-09-13 at 12 25 pm](https://cloud.githubusercontent.com/assets/15615381/18483020/7ad84424-79b0-11e6-8d66-f93546370bd7.gif)

4) `Article impression [artist follow]` sometimes fires when link to artist page is on page without actual follow button (and sometimes for wrong artist).

![image 2016-09-13 at 12 18 57 pm](https://cloud.githubusercontent.com/assets/15615381/18483003/66ba183c-79b0-11e6-91c7-a447b98da29d.png)

5) `Article impression [newsletter signup]` fires when box first scrolls into view, rather than when CTA (input form) is visible.

![image 2016-09-13 at 12 32 26 pm](https://cloud.githubusercontent.com/assets/15615381/18483043/91b4566a-79b0-11e6-9e77-2617139cfb70.png)

6) `Clicked article impression [related article]` doesn't fire for related articles.

![image 2016-09-13 at 12 41 33 pm](https://cloud.githubusercontent.com/assets/15615381/18483065/a9d8ec88-79b0-11e6-8843-8dd4248533d9.png)

7) Throughout, `destination_path` should be shortened to path rather than full URL (i.e., only include what's after 'artsy.net').

-----

Additional notes for superarticles:

1) `Article share` doesn't fire from social widgets at the top of the page.

![image 2016-09-13 at 12 35 20 pm](https://cloud.githubusercontent.com/assets/15615381/18483104/cd9adfaa-79b0-11e6-887f-91f5306b3115.png)

2) `Article impression [table of contents]` doesn't fire at all (unless this is an anomalous case?).

![image 2016-09-13 at 12 36 54 pm](https://cloud.githubusercontent.com/assets/15615381/18483120/e1d2945e-79b0-11e6-903f-fcd7093803c3.png)

**Comment by kanaabe** [comment]
@eessex let's pair on this one to get you familiar with our analytics

**Comment by eessex** [comment]
@joelauerbach - I'm looking at #2: Article impression [related article] -- do you want to return value of the related article links included in this?

**Comment by orta** [comment]
@joelauerbach ^ this might be a good opportunity for you to pair with eve and understand how everything connects behind the scenes too
