### ISSUE TITLE
Update Superarticles to support full screen headers in sub articles

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1445]
https://github.com/artsy/positron/issues/1041

**Comment by eessex** [comment]
@owendodd, should we make the header transparent, or just have it turn on once the user scrolls into the body?  If transparent, how should we handle the carousel?

**Comment by owendodd** [comment]
@eessex Let's handle it the same way we do the main article of the super article. So just having the logos + share on landing, and then nav fades in once you scroll into the body.

![screen shot 2017-05-22 at 12 19 28 pm](https://cloud.githubusercontent.com/assets/3196536/26318405/fde58716-3ee8-11e7-940f-389da00bac39.png)

**Comment by eessex** [comment]
@owendodd do we want to left align the title and intro paragraph for subarticles as well?

**Comment by owendodd** [comment]
I think headlines should be centered, intro paragraphs should be left aligned (we don't really use the intro paragraphs for features anymore). @eessex
