### ISSUE TITLE
Artworks with missing artists error

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#145]
Example pages:
https://www.artsy.net/artwork/discus-thrower-discobolus-roman-copy-of-myrons-bronze-original-of-the-5th-century-bc
https://www.artsy.net/artwork/egypt-old-kingdom-fourth-dynasty-great-pyramids-of-giza

**Comment by briansw** [comment]
From @mzikherman 
> its crashing on trying to do something with related artists
