### ISSUE TITLE
Duplicate S3 buckets

### ISSUE THREAD

**Issue by starsirius** [artsy/force#1459]
While working on https://github.com/artsy/force/issues/1429, I realized we are using 2 different buckets for the JSON pages, one is `force-staging`/`force-production` grabbed from the [`APPLICATION_NAME`](https://github.com/artsy/force/blob/3551ff9e3c57f7a2163f398c245ee954910954b7/desktop/apps/partnerships/routes.coffee#L24) env var, and the other is using `artsy-force-staging`/`artsy-force-production` from the [`S3_BUCKET`](https://github.com/artsy/force/blob/caed5bf630d71a083149ead10b464db565dddfa5/desktop/components/json_page/update.coffee#L8) env var. _I think_ we are also using the `S3_BUCKET` for compiled assets.

Note that the `force-staging`/`force-production` bucket was under `it@artsymail.com`, so an IAM user might not see the bucket.

cc @craigspaeth.

**Comment by craigspaeth** [comment]
I fixed a similar issue in [this PR](https://github.com/artsy/force/pull/989) but it looks like we still do this for partnership pages. I'm going to look into consolidating this on the JSON page component.
