### ISSUE TITLE
Reflection 40Xing

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force#1460]
A quick fix is we can fall through to normal rendering if Reflection hasn't cached a page. This might have regressed after [this refactor](https://github.com/artsy/force/commit/80445b650447251dd3fcfb0d02f7ace831f1bb3d#diff-219445cc9f999199f2ec28ad5ec8d214).

Alternatively/longer-term we should investigate if we need Reflection at all. We can do this by removing the `<meta name="fragment"` tags from a set of pages and compare organic traffic. We should also make sure robots.txt from the API isn't blocking requests from Google to render the page.

**Comment by dblock** [comment]
If we're looking for a set of pages I suggest a sitemapped set, such as, for example, all features from 2013, https://www.artsy.net/sitemap-features-2013.xml.

**Comment by christine-artsy** [comment]
hey all, here's the full context I could find from the last time removing Reflection was discussed: https://trello.com/c/zX9meXTy/381-unblock-api-artsy-net.
