### ISSUE TITLE
QA: search test

### ISSUE THREAD

**Issue by briansw** [artsy/force#1499]
Looks great just two details:

- [ ] apply border change on hover to existing border instead of inside so that elements don't bounce around https://cl.ly/04011o070Q2M
- [ ] similar to above, the focus should be applied to the exterior border

**Comment by xtina-starr** [comment]
@briansw I can definitely move the hover color change to the container div's border, but because the input's container is a div, it doesn't have a focus attribute so that can't really be moved to the outside.
