### ISSUE TITLE
Gene page (reaction-force) Q/A

### ISSUE THREAD

**Issue by broskoski** [artsy/force#1519]
- [x] Add minimum height to filter container (so loading is smoother)
- [x] Match "All Artists" width of button in production 
- [x] Check vertical alignment on filter buttons
- [x] Check resizing performance
- [x] Clicking ‘ALL ARTISTS’ does not reset the view to the initial fit-width rails.
- [x] Sort choice isn’t reflected in URL parameters.
- [x] Margin between artists rails feels inconsistent
- [x] Style spinner properly in preloading state
- [x] Make sure read more blurb is set up
- [x] Remove spinner when loadingState is complete
- [x] artist rail: space between img and tombstone too large, match what's done in brick view
- [x] artist rail: space between artworks 15px
- [x] artist rail: use artist follow button component and behavior from artwork pages (spacing/sizing/color issues)
- [x] tombstone text should be `#666`
- [x] heart should only appear on hover
- [x] 40px margin between artworks in brick view
- [x] too much space between last artist rail and LOAD MORE button
- [x] add transparent underline to LOAD MORE button so content below doesn't shift on hover

**Comment by alloy** [comment]
The ‘all artists’ button is wider, intentional?

### Before

<img width="203" alt="screen shot 2017-06-07 at 16 46 56" src="https://user-images.githubusercontent.com/2320/26884791-f6f41ef8-4ba0-11e7-857b-51edd57c62bf.png">

### After

<img width="245" alt="screen shot 2017-06-07 at 16 45 14" src="https://user-images.githubusercontent.com/2320/26884811-005426d2-4ba1-11e7-925f-8139ddf11874.png">

**Comment by broskoski** [comment]
@alloy Not intentional, thank you

**Comment by alloy** [comment]
The vertical alignment of the filter captions seems a tad too much to the bottom:

<img width="551" alt="screen shot 2017-06-07 at 16 51 57" src="https://user-images.githubusercontent.com/2320/26885046-bf23a786-4ba1-11e7-8a40-c70558608c23.png">

**Comment by alloy** [comment]
Resizing (especially continuously) the width of the window with the fit-width rails on screen feels sluggish and once even froze Safari.

**Comment by alloy** [comment]
Is the design that all the rails have the same height, even if not absolutely necessary for the content? E.g. the margin between these two rails feels a bit much:

<img width="1067" alt="screen shot 2017-06-07 at 17 36 43" src="https://user-images.githubusercontent.com/2320/26887344-12c78b22-4ba8-11e7-887f-29fd976bad5e.png">

**Comment by alloy** [comment]
Clicking ‘ALL ARTISTS’ does not reset the view to the initial fit-width rails.

**Comment by alloy** [comment]
Sort choice isn’t reflected in URL parameters.

**Comment by alloy** [comment]
Selecting and then unselecting ‘ONLY FOR SALE’ leads to different results, especially as loading the URL in a new window (or someone else’s computer) leads to the initial results (before selecting ‘ONLY FOR SALE’):

![gene-page-filter-weirdness](https://user-images.githubusercontent.com/2320/26887958-eb8e64ac-4ba9-11e7-9fde-8d124e66d34d.gif)

**Comment by alloy** [comment]
(Also spotted a spinner in that recording ^ that’s still shown on top of the gene description while the content is still loading.)

**Comment by yuki24** [comment]
Just one thing from me, tested on Safari 10.1.1 (12603.2.4):

![screen_shot_2017-06-07_at_1_59_29_pm](https://user-images.githubusercontent.com/386234/26893613-d0f0c574-4b89-11e7-9fed-888c8759a8c2.png)

**Comment by madeleineb** [comment]
@yuki24 I believe that's intentional—Read More should only appear if the wordcount of the description goes "below the fold"

Noted a phantom spinner that persisted even when all works were done loading in a filter state (https://www.artsy.net/gene/ceramic?dimension_range=%2A-24.0&medium=sculpture&price_range=50000-%2A):

![screen recording 2017-06-07 at 02 02 pm](https://user-images.githubusercontent.com/5949572/26893716-1ff42e9a-4b8a-11e7-82eb-7696c15ddf98.gif)

**Comment by briansw** [comment]
- [ ] artist rail: space between img and tombstone too large, match what's done in brick view
- [ ] artist rail: space between artworks 15px
- [ ] artist rail: use artist follow button component and behavior from artwork pages (spacing/sizing/color issues)
- [ ] tombstone text should be `#666`
- [ ] heart should only appear on hover
- [ ] 40px margin between artworks in brick view
- [ ] too much space between last artist rail and LOAD MORE button
- [ ] add transparent underline to LOAD MORE button so content below doesn't shift on hover
