### ISSUE TITLE
/artists page seems to not be rendering all artist results

### ISSUE THREAD

**Issue by broskoski** [artsy/force#1521]
From slack: 

> would the fact that artsy.net/artists gene rails that load artist tiles are behaving strangely have anything to do with @cab’s work? rails are loading fewer than the actual number of artists in the gene, eg. there appears to be only one artist in Emerging Art, or two in East Village: https://cl.ly/2Y371w20380k

**Comment by cavvia** [comment]
This was an issue with our career stage filters at the relevant API endpoints and was fixed in https://github.com/artsy/cinder/pull/230.
