### ISSUE TITLE
Interim full screen header updates

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1530]
We need to make a few tweaks to full screen header styling before larger updates in the next few weeks. 

![header on an article copy 57](https://user-images.githubusercontent.com/3196536/26953639-a4431f2c-4c79-11e7-92dd-0b22c498c276.jpg)

Essentially this is just moving some things around, and slightly restyling. Also means getting rid of the 'lead' / intro paragraph that we currently are using in some use cases ([https://www.artsy.net/article/artsy-editorial-2015-the-year-in-art](here) for example). We can just delete all of these (we are only doing this in ~5 places). 

Sketch: https://cl.ly/2y1C462D0v07

**Comment by kanaabe** [comment]
@owendodd Two Q's: 
1. We currently have a share nav on mobile that overlaps the feature -- do we want to hide this while the fullscreen is in view?
2. Super articles are configured to hide the author/date -- do we want to include this back in? 

This is what 2015 year in art ends up looking like:
![image](https://user-images.githubusercontent.com/2236794/27152108-ce103704-511a-11e7-9463-c6f09205f273.png)

**Comment by owendodd** [comment]
@kana yes and yes :)

I think for mobile we should have the share buttons fade in when you scroll a little further down.
