### ISSUE TITLE
Transparent nav bar lost in fullscreen header 

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#1538]
Pretty sure this is a bug, since this header has always been transparent. If this is instead intentional, then we should update the crop dimensions on fullscreen headers to accommodate for the reduced image space. 

![image](https://user-images.githubusercontent.com/2236794/27035284-c6c190ba-4f4e-11e7-91b4-f183b893fe33.png)

**Comment by eessex** [comment]
Looks like there are some new classes related to a split test, also noticed this same change is affecting the width of article pages.

![screen shot 2017-06-12 at 10 19 12 am](https://user-images.githubusercontent.com/1497424/27038331-a353ae10-4f58-11e7-93b5-92fbd4abdf25.png)

**Comment by eessex** [comment]
@katarinabatina asks we leave the menu as is for the duration of the test, and also notes that new article designs may make the change obsolete - https://artsy.slack.com/archives/C03JJ2RDG/p1497282366526849

**Comment by owendodd** [comment]
@eessex @kanaabe I chatted with Brian about this as well. I think it makes sense to leave for the time being and push forward on our alternate nav for editorial sooner rather than later
