### ISSUE TITLE
Fallback to larger or original image version instead of large in show pages

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#157]
_Issue:_ we currently use the "large" processed image version across the board on show pages, but given the way that the feed scales this forces images of odd proportions to render at a higher resolution than the image we're using
- [ ] if the image size being rendered is larger than the image source we are using we should fall back to pulling in the "larger" or "original" image

image of odd proportions:
![screen shot 2016-09-15 at 10 01 00 am](https://cloud.githubusercontent.com/assets/1863593/18553547/d28a294c-7b2e-11e6-8c47-99d9cce32df0.png)

image being rendered is larger than source:
![screen shot 2016-09-15 at 10 20 29 am](https://cloud.githubusercontent.com/assets/1863593/18553549/d46c163a-7b2e-11e6-9249-f08bd320f5de.png)

this or course also raises whether we should revisit the design implications of oddly sized images since in this case the artwork is not viewable within the viewport at a given time, but it is a rare edge case so isn't a priority at this time

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fallback to larger or original image version instead of large in show pages](https://trello.com/c/jbaj26ZT/576-fallback-to-larger-or-original-image-version-instead-of-large-in-show-pages)

**Comment by 1aurabrown** [comment]
I'll pick this up. This is going thru metaphysics, and we can fetch a resized image of a specific width through the image proxy. The largest these columns ever get is about 360px, so we'll just fetch something that safely accommodates that width, no matter what the aspect ratio.

**Comment by garrengotthardt** [comment]
thanks @1aurabrown !

**Comment by 1aurabrown** [comment]
For some of these, it seems there isn't an image that accommodates the max column width. For example this image:
the following fragment:
```
      image{
        url
        versions
        larger: url(version:"larger")
        original: url(version:"original")
        normalized: url(version:"normalized")
      	width
        height
        resized_original: resized(width:359, version:"original"){
          url
        }
        resized_larger: resized(width:359, version:"larger"){
          url
        }
        resized_normalized: resized(width:359, version:"normalized"){
          url
        }
      }
```
gives this response. The 'original' size is 'tall'. 'larger' is still not wide enough to accommodate the max column width. 'normalized' however is large enough, so I'll go with that. I am not really sure what it's intended use is though.
```
               {
          "id": "john-aslanidis-crosscurrent-no-1",
          "image": {
            "url": "https://d32dm0rphc51dk.cloudfront.net/B6JojBmosqbNqCDhQdH1Zg/tall.jpg",
            "versions": [
              "large",
              "large_rectangle",
              "larger",
              "medium",
              "medium_rectangle",
              "normalized",
              "small",
              "square",
              "tall"
            ],
            "larger": "https://d32dm0rphc51dk.cloudfront.net/B6JojBmosqbNqCDhQdH1Zg/larger.jpg",
            "original": "https://d32dm0rphc51dk.cloudfront.net/B6JojBmosqbNqCDhQdH1Zg/tall.jpg",
            "normalized": "https://d32dm0rphc51dk.cloudfront.net/B6JojBmosqbNqCDhQdH1Zg/normalized.jpg",
            "width": 373,
            "height": 1400,
            "resized_original": {
              "url": "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&width=359&height=1347&quality=95&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FB6JojBmosqbNqCDhQdH1Zg%2Ftall.jpg"
            },
            "resized_larger": {
              "url": "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&width=359&height=1347&quality=95&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FB6JojBmosqbNqCDhQdH1Zg%2Flarger.jpg"
            },
            "resized_normalized": {
              "url": "https://d7hftxdivxxvm.cloudfront.net/?resize_to=fit&width=359&height=1347&quality=95&src=https%3A%2F%2Fd32dm0rphc51dk.cloudfront.net%2FB6JojBmosqbNqCDhQdH1Zg%2Fnormalized.jpg"
            }
          }
        },
```

**Comment by 1aurabrown** [comment]
this is the show i was looking at: https://artsy.net/show/charles-nodrum-gallery-john-aslanidis
