### ISSUE TITLE
artwork sort broken on gene pages

### ISSUE THREAD

**Issue by cavvia** [artsy/force#1580]
The 'artwork year' sort bar (on the rhs) is unresponsive on gene pages:

![screen shot 2017-06-22 at 5 58 59 pm](https://user-images.githubusercontent.com/64404/27443843-ab5d01a0-5774-11e7-92b1-b19e0a71e6ce.png)

This seems to be the case for all gene pages. I don't see the request coming through to the API `/api/v1/filter/artworks` endpoint with the sort param, so I think this is a front-end issue.

**Comment by mzikherman** [comment]
Fixed with the rebuild of filters.

**Comment by cavvia** [comment]
Thanks for following up!
