### ISSUE TITLE
Analytics JavaScript is not consistently loading properly

### ISSUE THREAD

**Issue by xtina-starr** [artsy/force#1587]
It appears that the analytics JavaScript isn't always loading properly which causes the Search Results links on the search page to not be clickable. It's possible that the segment files are order dependent and some how getting out of sync (which prevents the analytics code to not load).

We should look into this to determine what is going on.

**Comment by yuki24** [comment]
While we were investigating we saw these two javascript errors in the console and these also may be preventing some js code from being loaded properly. However, some of us including myself did see that **sometimes** the search result page worked fine even with these errors.

<img width="380" alt="screen shot 2017-06-22 at 22 54 17" src="https://user-images.githubusercontent.com/386234/27499208-ce1f91b4-5830-11e7-938e-1b25bcaf9e97.png">

![screen shot 2017-06-22 at 22 51 31](https://user-images.githubusercontent.com/386234/27499211-d16c4a7e-5830-11e7-8b37-c360b0c86801.png)

**Comment by damassi** [comment]
@yuki24 - These values are set in yr `.env` file, right? https://github.com/artsy/force/blob/master/.env.oss#L69-L70

**Comment by yuki24** [comment]
@damassi these errors occur in production.

**Comment by kanaabe** [comment]
FYI I'm speaking with Parsely support about this issue so hopefully these Parsely-related errors will be resolved soon.

**Comment by kanaabe** [comment]
Looks like PR#1607 did the trick. Closing this but feel free to open if you think otherwise @yuki24

**Comment by xtina-starr** [comment]
thanks @kanaabe
