### ISSUE TITLE
[Bug] Homepage Rail times out

### ISSUE THREAD

**Issue by damassi** [artsy/force#1597]
When visiting artsy.net (production) it appears as though the homepage rail times out due to a regression in Metaphysics:

```
[{"message":"https://api.artsy.net/api/v1/gene/undefined? - {\"error\":\"Gene Not Found\"}"}]
```

I can no longer get to that rail view (not sure how I was there to begin with) so unfortunately I can't provide any more info!

**Comment by mzikherman** [comment]
Gonna close, this was probably some transient data thing.
