### ISSUE TITLE
error make ss

### ISSUE THREAD

**Issue by Branca** [artsy/force#16]
sorry but you can i help what is wrong ?

MacBook-Air-de-Admin:force-public admin$ make ss
APP_URL=http://localhost:5000 APPLICATION_NAME=force-staging API_URL=https://stagingapi.artsy.net foreman start
19:58:20 web.1  | started with pid 10702
19:58:20 web.1  | node_modules/.bin/forever node_modules/.bin/coffee --nodejs --max_old_space_size=960 index.coffee
19:58:20 web.1  | make[1]: node_modules/.bin/forever: No such file or directory
19:58:20 web.1  | make[1]: **\* [sf] Error 1
19:58:20 web.1  | exited with code 2
19:58:20 system | sending SIGTERM to all processes

**Comment by alloy** [comment]
Sorry for not responding sooner to this and thanks a lot for pointing this out. We are going to work on this right now.

**Comment by broskoski** [comment]
Looks like this might be due to not installing node modules! Try:

```
npm install
```
then
```
make oss
```

Closing now, feel free to reopen if you still have issues.
