### ISSUE TITLE
Artwork rail analytics is incorrect

### ISSUE THREAD

**Issue by orta** [artsy/force#166]
in [artwork_rail.js](https://github.com/artsy/force/blob/master/analytics/artwork_rail.js#L19)

This is hooked up wrong, "previous" for "next"

```js
$document.on('click', '.arv-carousel-arrow-prev', function(e){
    analytics.track('Clicked next on artwork rail carousel', { rail: railId(e) });
 });
```

**Comment by joeyAghion** [comment]
Fixed by https://github.com/artsy/force/pull/256
