### ISSUE TITLE
[Analytics] Created_account event fires when sign up via social buttons clicked

### ISSUE THREAD

**Issue by joelauerbach** [artsy/force#169]
`Created account` should only fire after the user actually creates an account. This issue is resulting in a lot of account creation events that aren't tied to any user in Gravity.

One way for us to monitor true account creations might be to pass the `Gravity user_id` as a property that overrides the Segment-issued user_id because the `identify` event fires after `created_account`, so currently `created_account` gets null user_ids.

![screen recording 2016-09-16 at 06 01 pm](https://cloud.githubusercontent.com/assets/15615381/18602494/91c22996-7c37-11e6-90f5-12e9d7f0a328.gif)

cc: @xtina-starr @broskoski @wrgoldstein @anipetrov

**Comment by anipetrov** [comment]
Bump on this one -- it is important to get this right as we are optimizing for user acquisition and retention. Would love to have an idea of when we can prioritize for this @craigspaeth @alloy (oh hi @alloy, so many more repos i can bug you in!!!!!!!)

**Comment by craigspaeth** [comment]
@anipetrov @joelauerbach Can we not deduce account creation from Gravity data? For instance, we have a ton of attributes on the user tracking login/signup https://github.com/artsy/gravity/blob/master/app/models/domain/user.rb#L56

**Comment by craigspaeth** [comment]
One reason I ask is b/c it's tricky to track account creation from Facebook/Twitter which redirect you out of Artsy and you can easily loose whether you're logging in or signing up. It's not impossible to implement this, but it's tricky so I'm wondering if there's not something more clever we can do in setting up this tracking pipeline.

**Comment by wrgoldstein** [comment]
Two cases where it matters quite a bit to have the event firing accurately are:

- in the context of a/b tests (which experience leads more people to create an account?) 
- marketing optimization (which campaign drove more signups? )

I don't think counting account creations in gravity will be able to solve for these, although I'd be game to talk further about whether there's a way.

**Comment by alloy** [comment]
@craigspaeth Have you done work on this item?
