### ISSUE TITLE
[Bug] Link to email consignments in Collector FAQ modal is broken

### ISSUE THREAD

**Issue by mikehrom** [artsy/force#1695]
From the homepage:
- Scroll to bottom
- click "Buying from Galleries FAQ" under "Collecting" (opens modal)
- click "Selling on Artsy"
- click link for "consign@artsy.net" on the right
- should open a 404 error

![broken-consign-1](https://user-images.githubusercontent.com/26879583/29044990-da1af968-7b8f-11e7-94e0-e8ae219c15a4.gif)

This modal can also be accessed on individual `/artwork` pages 
- Right hand side, "Read our [Collector FAQ](https://cl.ly/3Q1x0a2S433s)"

**Comment by damassi** [comment]
Fixed in admin.artsy.net
