### ISSUE TITLE
Infinite scroll on tag pages is not terminating correctly

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#1696]
On some tag pages when you hit the end of the result set (whether by paging thorugh infinite scrolls, or by pulling up a small result set to begin with), the page continues to display a spinner and issue requests to Metaphysics:

![tag](https://user-images.githubusercontent.com/140521/29046124-139fa2b6-7b94-11e7-85e7-df87e759cb24.gif)

**Comment by mzikherman** [comment]
Done'd with the rebuild of filters with Relay Modern. (plus additional check for counts being off to avoid this specific situation since apparently counts and data follow the uncertainty principle- you can only get one of those correct).

😈

**Comment by anandaroop** [comment]
Awesome! 🙌
