### ISSUE TITLE
Repeat filter requests from artist page

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#1726]
I noticed that each request to an `/artist/:slug` page triggers 3 separate API requests for filtered artwork results. They're each slightly different, but the repetition was a surprise so I'm wondering if it would be possible to consolidate or eliminate some. E.g., a load of `/artist/lynn-chadwick` results in these requests:

    /api/v1/filter/artworks?aggregations%5B%5D=total&artist_id=lynn-chadwick&page=1&size=9&sort=-partner_updated_at
    /api/v1/filter/artworks?aggregations%5B%5D=total&aggregations%5B%5D=gallery&aggregations%5B%5D=institution&aggregations%5B%5D=period&aggregations%5B%5D=medium&artist_id=lynn-chadwick&for_sale=true
    /api/v1/filter/artworks?aggregations%5B%5D=total&aggregations%5B%5D=gallery&aggregations%5B%5D=institution&aggregations%5B%5D=period&aggregations%5B%5D=medium&artist_id=lynn-chadwick

**Comment by cavvia** [comment]
Bumping this as it could make a big difference to our Elasticsearch traffic if we can consolidate these.

**Comment by joeyAghion** [comment]
Confirmed fixed by a combination of Metaphysics and Reaction changes over the last ~month.
