### ISSUE TITLE
Autocomplete results lead to non-human-friendly urls (for profiles, artworks)

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#173]
After the recent [switchover from Solr- to ES-powered autocomplete results](https://github.com/artsy/gravity/pull/10379), we are observing that selecting an autocomplete result brings you to a URL with a BSON id, rather than a human-readable slug.

This has to do with [the way search results are structured now](https://github.com/artsy/gravity/commit/1808695f3b0f68f6ad958566a73f680bf8fe9f13#commitcomment-19082026), and will be addressed with an update to Gravity.

After that's done, client-side changes may still need to be made to use the new `slug` field that will be returned with the search hit.

Liaison help request:
https://artsy.slack.com/archives/partner-success/p1474065713000318

Slack discussion:
https://artsy.slack.com/archives/platform-humans/p1474304180002790

**Comment by starsirius** [comment]
Thanks for the detailed / more actionable issue here! 👍

**Comment by anandaroop** [comment]
Looks like we're going back to the status quo of autosuggest results [returning the slug value](https://github.com/artsy/gravity/pull/10401/files#diff-b04e0fdd302f4521324606d747603d9fR37) as the `id` of the hit, so as soon as https://github.com/artsy/gravity/pull/10401 goes live, this should resolve itself.

**Comment by anandaroop** [comment]
Fixed for most models, Artwork are chugging away in Sidekiq, so closing this now.
