### ISSUE TITLE
Nav pages overflowing whitespace on width

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#1749]
Couldn't quickly determine what, but the page is overflowing right with whitespace pretty drastically.

**Comment by kanaabe** [comment]
@eessex I think this issue has to do with the `.screen-reader-text` class. The left positioning is adding a bunch of whitespace to the page. It's affecting any page that uses the nav which includes home. 

![image](https://user-images.githubusercontent.com/2236794/30174121-f80b23a8-93c7-11e7-9b42-8df987364eb1.png)

**Comment by eessex** [comment]
Ooh i see, there used to be an overflow-hidden on the body width -- will take a look today
