### ISSUE TITLE
Apply infinite scroll on auction lot pages

### ISSUE THREAD

**Issue by briansw** [artsy/force#175]
Page load is increasing significantly for artwork pages included in auctions with large lot sizes. 
- [ ] Load 50 works on initial page load
- [ ] Infinite scroll the remaining

cc @katarinabatina @devangt

**Comment by acjay** [comment]
One thought -- we should consider that with long pages and infinite pages is that it can make it difficult, or at least annoying, to reach the footer. With long pages, this is a problem, but you can at least drag your scroll bar to the bottom. With infinite pages, this triggers a load, and the footer "runs away from you".

Maybe we could just drop the footer links from infinite pages?

**Comment by katarinabatina** [comment]
@briansw I tend to think we should cap the works and provide an entrypoint back to the main sale page. Soon we'll provide a better browsing expereince there anyways and with sales topping out at 200lots I agree with @acjay that the expereince could start to feel clunky after a few scrolls down the page.
