### ISSUE TITLE
Change Magazine to Editorial in Nav

### ISSUE THREAD

**Issue by owendodd** [artsy/force#1788]
We have finally come to a consensus to depreciate the term 'Magazine' and fully switch over to 'Editorial'

**Comment by kanaabe** [comment]
🙌 🙌 🙌 🙌 🙌  Would it make sense to do this when we launch homepage?

**Comment by owendodd** [comment]
@kanaabe let's discuss the timing in person. Not sure what is best. I think we will also want to update urls to /editorial and /editorial/{article-title}

I was just excited about it and wanted to get the issue in :)
