### ISSUE TITLE
[Urgent] Need to randomize visits to one of two URLs based on UTM 

### ISSUE THREAD

**Issue by jessekedy** [artsy/force#181]
We're launching **SEO for Galleries** tomorrow via Marketo to ~80K people. We're trying to AB test which of these pages leads to more gallery applications -

A - https://www.artsy.net/gallery-partnerships?utm_medium=email&utm_source=marketo&utm_campaign=seo-for-galleries&utm_content=partnerships-a

B - http://pages.artsy.net/gallery-partnerships.html?utm_medium=email&utm_source=marketo&utm_campaign=seo-for-galleries&utm_content=partnerships-b

We don't need to change anything about the pages for this test. All we're looking to do is:

1. Person clicks on a link (https://www.artsy.net/partnership-opportunities)
2. Person is randomly redirected to URL A or URL B ~~(based on a UTM param)~~

cc @craigspaeth @garrengotthardt @wrgoldstein

**Comment by craigspaeth** [comment]
@jessekedy Can you let me know what the UTM param will look like by pasting in some sample URLs? Also just want to confirm that's _all_ that needs to be implemented, no extra tracking/analytics or feature work?

**Comment by wrgoldstein** [comment]
I think when we do this sort of process where we divert our traffic elsewhere our future selves will be grateful if we take a second to fire segment pageviews for the marketo pages

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Randomize visits to marketo GP page vs standard GP page](https://trello.com/c/8fv0rM0g/611-randomize-visits-to-marketo-gp-page-vs-standard-gp-page)
