### ISSUE TITLE
Gene page makes requests for increasingly large pages of results rather than paginating

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#1822]
Scrolling the gene page's artwork results triggers requests of increasing **page size** (but not **page number**) to the API. E.g.:

    Oct 11 15:19:16 rails-app1 stagingapi.artsy.net-ssl.access.log:  10.184.147.52 - - [11/Oct/2017:19:19:16 +0000] "GET /api/v1/filter/artworks?aggregations%5B%5D=medium&aggregations%5B%5D=total&aggregations%5B%5D=price_range&aggregations%5B%5D=dimension_range&dimension_range=%2A&gene_id=the-environment&price_range=%2A&size=10&sort=-partner_updated_at HTTP/1.1" 200 50243 "-" "-"
    Oct 11 15:20:39 rails-app2 stagingapi.artsy.net-ssl.access.log:  10.101.150.152 - - [11/Oct/2017:19:20:39 +0000] "GET /api/v1/filter/artworks?aggregations%5B%5D=medium&aggregations%5B%5D=total&aggregations%5B%5D=price_range&aggregations%5B%5D=dimension_range&dimension_range=%2A&gene_id=the-environment&price_range=%2A&size=20&sort=-partner_updated_at HTTP/1.1" 200 93309 "-" "-"
    Oct 11 15:20:40 rails-app1 stagingapi.artsy.net-ssl.access.log:  10.101.150.152 - - [11/Oct/2017:19:20:40 +0000] "GET /api/v1/filter/artworks?aggregations%5B%5D=medium&aggregations%5B%5D=total&aggregations%5B%5D=price_range&aggregations%5B%5D=dimension_range&dimension_range=%2A&gene_id=the-environment&price_range=%2A&size=30&sort=-partner_updated_at HTTP/1.1" 200 148401 "-" "-"
    Oct 11 15:21:35 rails-app2 stagingapi.artsy.net-ssl.access.log:  10.101.150.152 - - [11/Oct/2017:19:21:35 +0000] "GET /api/v1/filter/artworks?aggregations%5B%5D=medium&aggregations%5B%5D=total&aggregations%5B%5D=price_range&aggregations%5B%5D=dimension_range&dimension_range=%2A&gene_id=the-environment&price_range=%2A&size=40&sort=-partner_updated_at HTTP/1.1" 200 192711 "-" "-"

This appears to continue indefinitely. If someone actually scrolls to the bottom of the page and switches windows or walks away, the requests just keep coming.

**Comment by alloy** [comment]
This must be a bug in MP where it doesn’t properly translate a total size that a client wants to have to a page.

**Comment by anandaroop** [comment]
Oh wow, that sounds like it might also explain #1696

**Comment by mzikherman** [comment]
Closed with the rebuild.
