### ISSUE TITLE
Artworks with multiple consignable artists rendering problem

### ISSUE THREAD

**Issue by dzucconi** [artsy/force#1910]
![](http://static.damonzucconi.com/_capture/ABtrYfpAeK.png)

As seen on https://www.artsy.net/artwork/robert-rauschenberg-25-years-studio-signed-by-8-contemporary-artists-gemini-gel

**Comment by dzucconi** [comment]
https://github.com/artsy/force/blob/561f60df834bd641d94d8f84a2a50532d2b074e6/desktop/apps/artwork/components/commercial/index.styl#L70-L77

**Comment by sweir27** [comment]
👋 hi @dzucconi! Thanks for bringing this up. 😄
