### ISSUE TITLE
Upcoming auction reloads immediately, indefinitely

### ISSUE THREAD

**Issue by acjay** [artsy/force#1923]
For live sales scheduled far in the future, the artwork pages reload in a loop forever. As it turns out, this is because `ClockView` we schedules a reload for when the sale goes live using `setTimeout`, which [fires immediately](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Maximum_delay_value) if the number of milliseconds is greater than a 32-bit signed integer, or effectively more than 24.8 days away.

This may be the same cause as #1351.

**Comment by joeyAghion** [comment]
Such a good find!

**Comment by damassi** [comment]
For real 💯
