### ISSUE TITLE
Gene pages that sort by artist are empty or practically empty

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#1989]
Gene pages that sort by artist are empty, or mostly empty. Examples:

* https://www.artsy.net/gene/contemporary-asian-art
* https://www.artsy.net/gene/japanese-photography
* https://www.artsy.net/gene/old-masters

I'm not familiar with the internal logic, but one can inspect the page and see requests like the following being made (and successfully returning full pages of artists):

`https://api.artsy.net/api/v1/gene/contemporary-asian-art/artists?exclude_artists_without_artworks=true`

I didn't notice any console errors.

**Comment by mzikherman** [comment]
Closed with the rebuild.
