### ISSUE TITLE
 Ability to replace top image on /art-fairs when no fairs are live 

### ISSUE THREAD

**Issue by broskoski** [artsy/force#20]
_From @robertlenne on August 5, 2016 13:22_

@broskoski 

Awaiting design from @melnguyen 

_Copied from original issue: artsy/force-private#5442_

**Comment by alloy** [comment]
@robertlenne Is this still being worked on or will it? /cc @tayapage6 

As I understand it, the purpose of this was to sell that real estate to fairs that have year-around web presence?
