### ISSUE TITLE
Article Email Signup A/B Test

### ISSUE THREAD

**Issue by owendodd** [artsy/force#204]
Test between a full modal and a banner inserted above articles. Should be a 50/50 test for all users (that are not signed up to the newsletter) that land on an article. 

The modal should not display on landing but should fade in when a user begins scrolling. 

When a user closes either it should not display for 30 days. 

@kanaabe How long do you think we will need to run this test for significant results. 

@wrgoldstein Could you confirm that we don't have any other tests running atm? 

![screen shot 2016-09-26 at 2 38 28 pm](https://cloud.githubusercontent.com/assets/3196536/18847264/7f3a32f6-83f7-11e6-84e8-5d633abfed51.png)

Sketch file: https://cl.ly/3E451M141N1F

**Comment by owendodd** [comment]
We should run the test for a min of 10 days

**Comment by wrgoldstein** [comment]
Note if you run the test for 10 days and we show the modal again after 30 days we won't know how that reappearance will affect users before making a choice.  Probably an acceptable limit though.

The only other test I know of is the forced inquiry test, which shouldn't conflict with this one.  So you're 👍
