### ISSUE TITLE
Sidebar: Move medium to top, change period to reverse chronological order

### ISSUE THREAD

**Issue by briansw** [artsy/force#206]
- [x] Move medium to top
- [x] Order decades in reverse chronological order to be consistent with /collect

**Comment by 1aurabrown** [comment]
ok. fyi i think we need to do some gravity work to get more than 10 partners in the aggregations response.

**Comment by 1aurabrown** [comment]
@briansw do we want the reverse-chronological order to happen everywhere? in that case i'll make the change on metaphysics

**Comment by 1aurabrown** [comment]
@mzikherman can we modify the gallery and institution aggregations on the artwork filter end point to return all aggregations, not just the first 10?

**Comment by briansw** [comment]
>@briansw do we want the reverse-chronological order to happen everywhere? in that case i'll make the change on metaphysics
@1aurabrown could you point out where else we're using these filters? I'm only aware of the artist page and /collect which is already in reverse chronological order.

**Comment by 1aurabrown** [comment]
@briansw I believe you're right about that. But going forward, is it something where, if we were to use this metaphysics endpoint in other pages, we will want to order the periods differently each time, or do you think it is likely that we'll always want them to be ordered the same way? In other words, is there any reason _not_ to put this in metaphysics?

**Comment by briansw** [comment]
@1aurabrown if you're only referring to future period filter lists, yes, we'll always want those in reverse chron.

**Comment by mzikherman** [comment]
@1aurabrown sure, do you mind taking the lead on that? I can help pair if needed. It could be useful to get more people involved in the filter/ElasticSearch -> Metaphysics dance.
