### ISSUE TITLE
Jobs page nav broken

### ISSUE THREAD

**Issue by eessex** [artsy/force#2073]
Noted by Michelle Sarhis- 

Some Navigation items on https://www.artsy.net/jobs are erroring on click. 
<img width="646" alt="screen shot 2018-01-10 at 9 05 00 am" src="https://user-images.githubusercontent.com/1497424/34776664-a0a37c70-f5e5-11e7-8200-71f6d5ae673b.png">

Also, the last menu is displays a title of Null.
<img width="429" alt="screen shot 2018-01-10 at 9 05 29 am" src="https://user-images.githubusercontent.com/1497424/34776668-a26ab82a-f5e5-11e7-9499-49f6e1fb7f4b.png">

**Comment by mzikherman** [comment]
Fixed, there was a job with no category set (its a temporary posting anyhow).
