### ISSUE TITLE
IA Email signup QA

### ISSUE THREAD

**Issue by owendodd** [artsy/force#212]
Could we  left-align the text header, form, etc with the body text?

Also noticed that the rule does fully go across the screen, is that possible? If not could we make that rule the width of the body  and centered?

Thanks! 🌴

![img_2676](https://cloud.githubusercontent.com/assets/3196536/18926008/19143d9e-8584-11e6-827a-b32fc34de3b7.PNG)

**Comment by kanaabe** [comment]
@owendodd updated in ST, lmk if it looks good to you!

**Comment by owendodd** [comment]
@kanaabe 🙌
