### ISSUE TITLE
Artist follow on the main carousel of /artists/ does not work 

### ISSUE THREAD

**Issue by anipetrov** [artsy/force#218]
Follow button on the main carousel of /artists/ does not work -- follow widget does not fire and the follow doesn't stick.
![screen recording 2016-09-29 at 16 21](https://cloud.githubusercontent.com/assets/8701687/18970884/11354d1a-8661-11e6-94cd-a216ab252a5f.gif)

cc @robertlenne @broskoski

**Comment by eessex** [comment]
The carousel at the top seems to be loading artworks rather than artists, so the API request to /artists is giving a 404.

**Comment by katarinabatina** [comment]
Ok wrapped this up this morning, people were putting in artwork links so it made everything break. I replaced the links and told folks to only link to artist pages.
