### ISSUE TITLE
Artist Card bugs

### ISSUE THREAD

**Issue by broskoski** [artsy/force#22]
_From @briansw on July 29, 2016 14:5_
- [x] When artist is dead, "b. 1940" should become "1946–1999" eg: https://cl.ly/0z2H2P2A2q2z https://www.artsy.net/artist/martin-wong
- [x] When anything other than "born" precedes birth year don't display "b." eg: https://cl.ly/1E0a3u0m3J3Z https://www.artsy.net/artist/bernadette-corporation

_Copied from original issue: artsy/force-private#5427_

**Comment by alloy** [comment]
Seems all done

**Comment by briansw** [comment]
@alloy this still is an issue. See screenshot below and link for reference: https://www.artsy.net/artist/jonathan-horowitz/related-artists

![screen shot 2016-12-06 at 4 06 19 pm](https://cloud.githubusercontent.com/assets/1022172/20943559/f755965a-bbcd-11e6-9a96-762d14d8d0e7.png)

**Comment by briansw** [comment]
@alloy the Martin Wong example as well: https://www.artsy.net/artist/jonathan-horowitz/related-artists

![screen shot 2016-12-06 at 4 07 49 pm](https://cloud.githubusercontent.com/assets/1022172/20943605/3034ff60-bbce-11e6-88b3-3abfdb50cd3c.png)

**Comment by alloy** [comment]
@briansw Aha, thanks for the updates 👍 

I think we do all of these shenanigans in MP already, so Force should just display that directly.
