### ISSUE TITLE
Better asset bundling/uploading for faster deploys?

### ISSUE THREAD

**Issue by broskoski** [artsy/force#23]
_From @mzikherman on July 21, 2016 17:41_

It'd be cool to be able to deploy in a way that can figure out which assets have changed from a prior deploy/S3 bucket, and only need to re-bundle and upload those that are changed.

_Copied from original issue: artsy/force-private#5395_

**Comment by alloy** [comment]
@craigspaeth Do you want to move this issue to https://github.com/craigspaeth/bucket-assets and/or how feasible you think this is in the short term?
