### ISSUE TITLE
Search results in fair microsite not clickable

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#232]
https://www.artsy.net/frieze-london-2016

Search 'Marina', click Marina Abramovic...nothing. I _think_ you should be routed to https://www.artsy.net/frieze-london-2016/browse/artist/marina-abramovic-1

**Comment by alloy** [comment]
This specifically happens in Chrome, e.g. works fine in Safari.

**Comment by alloy** [comment]
This got fixed in #275.
