### ISSUE TITLE
'Read More' content fold appears on top of contact gallery ribbon

### ISSUE THREAD

**Issue by erikdstock** [artsy/force#235]
https://www.artsy.net/artwork/andy-warhol-flowers-ii-dot-72-6

When scrolling down, the purple ribbon floats under the 'read more' line.

![image](https://cloud.githubusercontent.com/assets/9088720/19123080/4732b530-8afb-11e6-8239-5fa1a3c94a76.png)

**Comment by 1aurabrown** [comment]
I think this may have been fixed? (It may have even been me as I thought I'd looked at this before). This is what I see:
![screen shot 2016-11-28 at 4 48 30 pm](https://cloud.githubusercontent.com/assets/3171662/20674843/9c000428-b58a-11e6-8b4a-7bda4964ad3d.png)

**Comment by alloy** [comment]
Totally fixed.
