### ISSUE TITLE
Deprecate `NODE_ENV=staging`

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#2371]
cc @joeyAghion @izakp @damassi 

https://artsy.slack.com/archives/C2TQ4PT8R/p1523983729000635

Basically, we should run `force-staging` with `NODE_ENV=production`.

We should go over places that are env-dependent in Force, and decide if they are ok to leave environment-dependent (and remove any 'staging' references), or replace with their own more granular env flag.

**Comment by izakp** [comment]
May want to sync with @saolsen as he works on https://github.com/artsy/force/pull/2352
