### ISSUE TITLE
Broken auction link on homepage hero

### ISSUE THREAD

**Issue by zephraph** [artsy/force#2544]
Clicking this auction on the homepage's hero carousel results in a [404](https://www.artsy.net/finarte-modern-and-contemporary-art-1). 

![image](https://user-images.githubusercontent.com/3087225/40320701-2a20a180-5cf2-11e8-88bf-c2e276721d0b.png)

**Comment by zephraph** [comment]
@kanaabe This one might actually be something to address?

Current link is:
https://www.artsy.net/auction/finarte-modern-and-contemporary-art-1

Working link is:
https://www.artsy.net/auction/finarte-modern-and-contemporary-art-1

**Comment by kanaabe** [comment]
Oh yes! Good call, I'll notify the internal team that manages this. Thanks for the find!

**Comment by kanaabe** [comment]
Updated!
