### ISSUE TITLE
Switch to master/release deploy scheme?

### ISSUE THREAD

**Issue by broskoski** [artsy/force#26]
_From @mzikherman on July 28, 2016 17:47_

Something like:

> The default branch for this repo is master. All development and PR's are done against/into that branch. Upon a successful merge, the master branch will get automatically deployed to Heroku's staging environment. When you are ready to deploy to production, open a PR from master to release. CI will automatically deploy to Heroku's production environment on a successful merge to the release branch.

This way, rather than use a janky Semaphore UI to deploy to prod, we can use the familiar GitHub PR UI to kick off a deployment. We can also easily use the GitHub UI to see past deployment PR's and see what's been deployed when, and each deploy remains reviewable as a PR.

_Copied from original issue: artsy/force-private#5424_

**Comment by alloy** [comment]
I have no real opinion for or against. If this is trivial to setup and no other devs on this project object, then go for it 👍

**Comment by mzikherman** [comment]
Cool, I'm still very much in favor of this over the current flow, so will give it a shot.

**Comment by 1aurabrown** [comment]
I'm not sure how to QA this, Kana deployed this way last week and I don't think there was any problem, or if there was I didn't hear about it because I was offline. I think after a few successful deploys we can consider this closed.

**Comment by mzikherman** [comment]
Yea, this looks done 👍 

Should we do it for microgravity too?
