### ISSUE TITLE
Events connected to a show should display in chronological order

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#276]
![screen shot 2016-06-23 at 10 52 41 am](https://cloud.githubusercontent.com/assets/1863593/16307828/ae9e0fde-3930-11e6-87dd-85ae29623108.png)

https://www.artsy.net/show/espace-louis-vuitton-munchen-chantal-akerman-slash-annette-messager-les-approches
- [ ] it looks as though the events are currently ordered in the order they were created or randomly but should be ordered in chronological order top to bottom

https://cms.artsy.net/partner_shows/espace-louis-vuitton-munchen-chantal-akerman-slash-annette-messager-les-approches?current_partner_id=espace-louis-vuitton-munchen

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Events connected to a show should display in chronological order in force show pages](https://trello.com/c/0j0kAsCp/534-events-connected-to-a-show-should-display-in-chronological-order-in-force-show-pages)

**Comment by gnilekaw** [comment]
Update: Submitted a PR fixing this, but after convo with Roop and Matt, we decided to make the fix on Gravity. See https://github.com/artsy/force/pull/503#issuecomment-266871958
