### ISSUE TITLE
Error state for logging in

### ISSUE THREAD

**Issue by owendodd** [artsy/force#281]
There should be an error state for the login modal. 

Right now, trying to log in w/o inputing an email address takes you to this:

![screen shot 2016-10-13 at 11 01 22 pm](https://cloud.githubusercontent.com/assets/3196536/19374387/304f92a8-9199-11e6-8eaf-bf7e4e2fa5a6.png)

**Comment by alloy** [comment]
I’m not able to reproduce this. If you still can, can you please provide some steps or a video?
