### ISSUE TITLE
QA: Artist page filters

### ISSUE THREAD

**Issue by briansw** [artsy/force#285]
- [x] Truncate names sooner in the sidebar so they don’t crash into the content area (see screenshot below)
- [ ] The filters seem to load slow. Do you have any suggestions for how we could speed this up? 

![screen shot 2016-10-17 at 8 41 18 am](https://cloud.githubusercontent.com/assets/1022172/19438971/45ef5630-944a-11e6-87eb-16121a472240.png)

Related to: https://github.com/artsy/force/issues/66 https://github.com/artsy/force/issues/206

**Comment by craigspaeth** [comment]
@1aurabrown @briansw Speeding up the slow loading filters is a bit more involved. If performance issues are accumulating, let's plan to aggregate an ordered hit-list of slow performing places and tackle it as one bigger item b/c the work will likely be related and it'll be helpful to have that bigger/aggregated picture when tackling it. With that in mind, I'll close this issue.
