### ISSUE TITLE
Logged out Iconic Artists Rail update

### ISSUE THREAD

**Issue by briansw** [artsy/force#291]
Trending via most searched will not be available to us for an extended period of time so we'd like to swap it out with most saved artworks and change the name of the rail:

- [x] Change rail name to "Works by Popular Artists"
- [x] Power the rail using the trending API via artists with most follows

### Module
<img width="1221" alt="screen shot 2016-10-18 at 11 02 45 am" src="https://cloud.githubusercontent.com/assets/1022172/19483482/7d10187e-9522-11e6-8add-8cad1c15c6fe.png">

Related: https://github.com/artsy/force/issues/292

**Comment by alloy** [comment]
(Updated description to state that the data should be based on follows instead of saved artworks.)

**Comment by alloy** [comment]
Should be fixed with https://github.com/artsy/force/issues/297 & https://github.com/artsy/metaphysics/issues/444
