### ISSUE TITLE
Logged in Artists to Follow rail update

### ISSUE THREAD

**Issue by briansw** [artsy/force#292]
Trending via most searched will not be available to us for an extended period of time so we'd like to swap it out with most saved artworks and change the name of the rail:

- [x] Power "Most Popular" tab with the trending API via most artists with most follows

![screen shot 2016-10-18 at 11 06 34 am](https://cloud.githubusercontent.com/assets/1022172/19483721/51b5bafc-9523-11e6-9332-bc17548ff099.png)

Related: https://github.com/artsy/force/issues/291

**Comment by alloy** [comment]
https://github.com/artsy/metaphysics/issues/438

**Comment by alloy** [comment]
(Updated description to state that the data should be based on follows instead of saved artworks.)

**Comment by alloy** [comment]
Fixed by https://github.com/artsy/gravity/pull/10480
