### ISSUE TITLE
[Differentiation] Team Channel: Article Signup

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#40]
@owendodd commented on [Tue Aug 09 2016](https://github.com/artsy/force-private/issues/5461)

This should be integrated with Marketo to fit in with the marketing workflow.

![screen shot 2016-08-09 at 3 03 17 pm](https://cloud.githubusercontent.com/assets/3196536/17529724/7262c5fa-5e42-11e6-987b-56774b4f63d0.png)

Sketch file here:
https://www.dropbox.com/s/ah416g2i2h0cp9w/ArticlePage.Differentiation_06.sketch?dl=0

Overview: #5456

**Comment by eessex** [comment]
@owendodd - the sketch file here doesn't include the newsletter, possible to send?

**Comment by owendodd** [comment]
@eessex https://cl.ly/3t1v371F3i1T

Oops!

**Comment by eessex** [comment]
@owendodd -- will this be replacing the popup banner or run alongside it?  Noticed there are some issues open with the old signup (https://github.com/artsy/force/issues/127)
