### ISSUE TITLE
Purchase request AB test details

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/force#434]
The criteria I have are that
- the work must have a fixed price (not a range) displayed. related gravity ticket: https://github.com/artsy/gravity/issues/10607
- Test outcome should be random on page load, not locked to the user after the first outcome.
- Upper limit to artwork price for eligible artworks?

Let's add other information about the AB test here.

**Comment by anipetrov** [comment]
Why this condition?
>Test outcome should be random on page load, not locked to the user after the first outcome.

**Comment by tayapage6** [comment]
Goals of test
Determine if this new CTA increases inquiries from either flow
If we get more qualified inquires through the Purchase flow we would continue to invest in more e-commerce like features.

Test parameters
Web-only, for all artworks with an exact price entered.
Limit to the minimum dollar value of artworks to be able to get enough inquires to achieve statistical significance in 4 weeks.

Test cells
50% of the time an artwork page is loaded, show current message text field and contact button
50% of the time show the new Purchase flow.

The winning cell is the cell that drives the most total requests (so needs to run at least 30 days?) overall.

Also track # of inquiries, $ value, # of sales from each flow, time to sale, 3 way handshakes, and bounce rate to give context to the data.

**Comment by tayapage6** [comment]
@anipetrov since we have so few collectors making inquiries, to truly get a sense of whether the new flow is winning, i'm concerned that if a high intent collector gets into one cell or the other they can bias the results.

**Comment by anipetrov** [comment]
@tayapage6 I chatted with my team and we would recommend that we stick to the traditional way of splitting our audience. The randomization on the user level should already take care of the problem you are describing and we take into account the low conversion rates when we give out test time to run estimates. 

There are some drawback on going with the originally proposed design (called "within-subject design" in statistical literature) for the test:
* my sense is that there are too many steps and interrelated factors to consider that a user converting on one artwork as opposed to another could be easily attributed to the difference in purchase CTA
* probably the largest drawback of within-subject design tests, "carryover effects" : how will the outcomes be influenced by the user experience of going through different flows if you inquire multiple times in the duration of the test
* we have no control on how many times different subjects will be exposed to the test

Some literature on the strengths and weaknesses of within-subject tests: 
https://web.mst.edu/~psyworld/within_subjects.htm
https://faculty.washington.edu/agg/pdf/Gwald_PsychBull_1976.OCR.pdf

cc @wrgoldstein @joelauerbach

**Comment by tayapage6** [comment]
@anipetrov I defer to your expertise. Originally when I thought we were just going to test the purchase button not this whole 'checkout' flow i was less concerned with the other influencing factors. I'll update accordingly

**Comment by 1aurabrown** [comment]
Are the following things agreed upon so I can go ahead and commit them to code? Feel free to update the original list i posted:
- desktop only
- randomized by user, not pageload
- artworks with a price (not a range) that is under some upper bound

**Comment by 1aurabrown** [comment]
This may require coordinating with someone on core to accurately track three-way handshakes, as I'm unfamiliar with how that system works. @anipetrov perhaps we can touch base since you know much more about analytics than i do to map out exactly which events will be sent.

**Comment by 1aurabrown** [comment]
I am going to close this particular issue because after talking to annie there is nothing to do for the AB test that isn't already done, other than uncommenting the line where i override its outcome to display the flow for all users.
