### ISSUE TITLE
homepage banner should be swipeable on tablets

### ISSUE THREAD

**Issue by katarinabatina** [artsy/force#440]
Browsing Artsy on an ipad in safari and am unable to swipe through the banners on the homepage.

**Comment by broskoski** [comment]
Note: We can make the homepage banners use flickity and that should automatically add swipability

**Comment by broskoski** [comment]
OK, after looking at this I see two options:
1. Convert the banner section from a custom job to use Flickity (the only caveat here is that Flickity doesn't support fading transition, so it would have to be a swipe like all the other carousels).
2. Add a jQuery (I know) plugin to support swipe events (like: https://github.com/mattbryson/TouchSwipe-Jquery-Plugin )

If converting the homepage to a sliding transition is NBD then I can go ahead and do that.

**Comment by alloy** [comment]
I’d argue that the _only_ transition that makes sense with a swipe gesture is a carousel transition. That is, the idiom is that the elements are supposed to ‘stick’ to the fingers performing the gesture.

Was there a specific need for a fade transition?

**Comment by broskoski** [comment]
@katarinabatina can you make the call? Can we kill the fading transition on the homepage carousel?

**Comment by katarinabatina** [comment]
Unfortunately not, our banners are just too massive to have them "moving across the screen" as they transition. Sooooorrrrrryyyyyy :(

**Comment by alloy** [comment]
I’m not sure I follow what the problem is with them being massive? Just what it visually looks like when we quickly animate a 2000px wide banner across the screen or a performance issue?

**Comment by broskoski** [comment]
No problem on my end, just want to avoid anyone complaining after the transition is no longer a fade :)

**Comment by broskoski** [comment]
Oh missed @katarinabantina's comment. :wave:

**Comment by alloy** [comment]
@katarinabatina bump

**Comment by katarinabatina** [comment]
sorry looks like my last comment neeever made it here. I think having a massive banner that moves across the screen is distracting (visually) which is why I'd prefer us to maintain the current animation when a user swipes.

**Comment by broskoski** [comment]
Soooo @katarinabatina , I started doing this by just hooking up the swipe event to the current homepage banner component. _Only_ doing the swipe transition on iPad will be a little wacky as it will mean a completely different implementation just for iPad. I'm fine to do it but it will definitely take a bit longer than just hooking up the swipe event.
