### ISSUE TITLE
EOY Feature

### ISSUE THREAD

**Issue by eessex** [artsy/force#443]
**Post Launch Issues**
- [x] Firefox scrolling issue
- [x] Add share buttons to intro text and moment text: https://cl.ly/0x0s112Q0o29
- [x] Play button not working (clicking elsewhere on the video does work)
- [x] Get rid or Border top and bottom on sub article headline
- [x] Check analytics, sync w/ Joel, get things up and running in Looker @kanaabe 
- [x] Arrows not vertically centered for Christo slideshow on mobile: https://cl.ly/0J3U3D1u1334

**QA For Initial Launch**

🌟  Eve 🌟 
- [x] Move intro para to below the main headline (https://files.slack.com/files-pri/T02531TU5-F3E5GM42F/screen_shot_2016-12-13_at_12.00.06_pm.png)
- [x] MOBILE Some issues w/ headlines in the header on mobile getting clipped: https://cl.ly/0y1s381Q1c1K, if we bump the text size down to 30px we should be good.
- [x] MOBILE Increase size of these images (30px margin left/right): https://cl.ly/0e1J2p0m0L1d
- [x] MOBILE Minimize space above / below Christo slideshow: https://cl.ly/3g2O3E080K40
- [x] Last section not fading in
- [x] Add font-weight: normal; to the 'Back to Magazine' link in the header

🎱  Kana 🎱  
- [x] Video bugs on mobile
- [x] Updates to super article header logos (requested by UBS), drop the "Presented..." language, move logo to the left side w/ artsy, add in a plus: https://cl.ly/0v0x0M2z3v1T white logo is here: https://cl.ly/2E1L0Z3Q1g3O incase that is hard coded, otherwise I'll update all logos in writer
- [x] Add in Back to Magazine link as per ^
- [x] Handle sub article clicks from MG (need to redirect to Force instead)
- [x] Create a redirect from the super article to /2016-year-in-art
- [x] Create final route
- [x] Text transform all caps for this line of text: https://cl.ly/3x1L383B3443
- [x] Weird placeholder cropping / video cropping in safari: https://cl.ly/2X1n222n2G1d

**Additional QA / Nice to have (in order of importance)**
- [ ] Smoother header scroll on mobile 
- [ ] Order articles on super article nav
- [ ] Check eigen-web-association
- [x] Share buttons
- [x] Auto scrolling in the header 🐳
- [x] Some line funkiness here (between racial inequality and cultural heritage): https://cl.ly/1w31063O0x2e
- [ ] Some indication that the nav is hoverable?
- [x] Smaller intro text on mobile
- [x] Make ubs logo same size as artsy
- [x] Top align carousel
- [x] 20% black opacity on video
- [x] Video controls a little off: 
![image](https://cloud.githubusercontent.com/assets/2236794/21129816/4e4af1e0-c0d2-11e6-9b20-bc2a215ce280.png)
- [x] MOBILE Image set funkiness: https://cl.ly/1N0P3q0Z2y1U and https://cl.ly/31442K421h38
- [x] Responsive image set
- [x] Clicking anywhere on the screen when the feature initially loads should scroll the user 200px down the screen 
- [x] This line is intersecting the other line for some reason, should have the same spacing as elsewhere: https://cl.ly/463Q1D2b342I
- [x] Caption support for carousel
- [x] Indent text 20px: https://cl.ly/301i360v0A2r
- [x] Slow down transition after clicking a link in the intro
- [x] Christo image set is skipping images
- [x] Video controls bugs
- [x] Mobile super article nav hamburger clickable
- [x] Link underline should be border-bottom instead
- [x] max width of 900 for intro block (including rules): https://cl.ly/2q1C0k353w0o
- [x] Max omg height of 70vh for Images in sub articles
- [x] Updates lines in header so they all hit the same bottom point on the screen: https://cl.ly/1a2l1S1s3w0G

----
Deploy

- [x] Update EOY_2016_SLUGS with finalized article slugs
----
Live
- [x] Fade in moments quicker?
- [x] Fade-in sections once 
- [x] Moment headers in intro should have a hover state of 60% opacity
- [x] Figure out Parsely tracking
- [x] Add designs for last 3 moments (pending sketches from Owen)
- [x] Add tests
- [x] Link current year sub-articles
- [x] Debug body fadein
- [x] Add current year's super article
- [x] Add Cristo images to slideshow
- [x] Video controls for Guerilla Girl video (?)
- [x] Hide html background video controls on mobile
- [x] Super-sub-article styling
- [x] Sailthru tags
- [x] Exclude auction reminder
- [x] Debug animation choppiness 
~~- [ ] Include metadata for search/social~~ (halley has added this on her pre-launch todos)
~~- [ ] Analytics (?)~~ (events below)
~~- [ ] Mobile theme~~
~~- [ ] QA Mobile~~
~~- [ ] QA Desktop~~

**Nice to Have**

- [ ] Explore speed improvements -- https://www.buzzfeed.com/daozers/what-its-like-to-work-on-buzzfeeds-tech-team-during-record-t?utm_term=.xmN5Yb33L#.xgAzoejjk
- [x] Center articles in dropdown when there aren't enough to fill the space: https://cl.ly/1Z2I3f262u2A @kanaabe 
- [ ] Placeholder images for the three other videos
- [x] make super article nav more condensed, text should be 20px, w/ 15px margin above and below: https://cl.ly/2n080Y3S2A3w

**Comment by owendodd** [comment]
Let's make the font size for the title (year in art, 2016) 7vw. 
And the moment headers in the intro 4vw

**Comment by owendodd** [comment]
- [ ] Add sailthru meta tags
- [ ] Add event tracking for scrolling into article body
- [ ] Add event tracking for clicking UBS / Planet Art Logos
- [ ] Add event tracking for clicking Planet Art download link

**Comment by owendodd** [comment]
Switch body copy to 22px 1.6 line height on desktop

**Comment by owendodd** [comment]
- [ ] Super article header hover state. There is 10px of white to the left of the hover that should also be gray, its more noticeable w/ more articles in the carousel. The white should be grey as well on hover.
![screen shot 2016-12-08 at 6 01 29 pm](https://cloud.githubusercontent.com/assets/3196536/21031346/e8b2c902-bd70-11e6-9115-7302a670248b.png)

**Comment by owendodd** [comment]
- [ ] Extend vertical lines 400px past the bottom of the moment

**Comment by owendodd** [comment]
- [ ] Cap max width of intro paragraph at 900px
- [ ] Add rule on the right side

![screen shot 2016-12-08 at 6 04 15 pm](https://cloud.githubusercontent.com/assets/3196536/21031433/7d263862-bd71-11e6-807a-19261e3d8ba6.png)

**Comment by owendodd** [comment]
- [ ] Switch images in Christo slideshow with these 6 (in order) https://cl.ly/3E2v340W3l0O

**Comment by owendodd** [comment]
- [ ] Get rid of persistent rule at the bottom of the screen for the intro, so that it matches the bottom section a bit more. Some minor spacing may need to be worked out as well. 

So it would look like this:
![screen shot 2016-12-09 at 12 24 13 pm](https://cloud.githubusercontent.com/assets/3196536/21058122/8d68aa68-be0a-11e6-9a55-23b719a86e57.png)

as opposed to this:
![screen shot 2016-12-09 at 12 24 31 pm](https://cloud.githubusercontent.com/assets/3196536/21058127/96d818e0-be0a-11e6-9741-97615362d2bd.png)

**Comment by owendodd** [comment]
- [ ] Change controls on slideshow to match line weight throughout feature (svg here: https://cl.ly/0y3X1o201c07)

![screen shot 2016-12-09 at 1 58 11 pm](https://cloud.githubusercontent.com/assets/3196536/21060897/d709ccc6-be17-11e6-8b49-9fca59d82e71.png)


Hover:
![screen shot 2016-12-09 at 1 58 28 pm](https://cloud.githubusercontent.com/assets/3196536/21060898/dc2c0f20-be17-11e6-91fd-2ff13bbf385c.png)

**Comment by owendodd** [comment]
- [ ] Looks like the black line is 1px too far to the right 😏
![screen shot 2016-12-09 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/3196536/21061895/5c6acff6-be1c-11e6-96a4-17d0ef57d326.png)

**Comment by owendodd** [comment]
More type size updates!

- H2's should be a be 4vw w/ a min- size of 90px until it hits the mobile breakpoint which should have a size of 40px

- H1's should be 7vw w/ a min-size of 120px until mobile which should be 50px.

**Comment by kanaabe** [comment]
@owendodd ah the white hover state for the nav is for the arrow. was probably hiding the arrow before since we only had one article in the carousel.

![image](https://cloud.githubusercontent.com/assets/2236794/21069142/27c92a08-be45-11e6-8880-c278f17965a2.png)

**Comment by owendodd** [comment]
@kanaabe Re the above, Realizing that this actually just applies to the header on the landing page, which has these white spaces to the left of each article
<img width="252" alt="screen shot 2016-12-12 at 4 16 51 pm" src="https://cloud.githubusercontent.com/assets/3196536/21117218/bee5be5e-c086-11e6-9f90-f0d71710a39f.png">

**Comment by eessex** [comment]
@owendodd - can't see the line error referred to in the first checkbox, are you still getting this?

**Comment by owendodd** [comment]
@eessex Nah, looks good now 👍

**Comment by halleyjohnson** [comment]
Can't seem to edit the above, but @kanaabe the captions in the Guerrilla Girls section—the video (first asset in section) is pulling the same caption as the second asset in the section. They're right on the backend

![screen shot 2016-12-14 at 09 52 04](https://cloud.githubusercontent.com/assets/10982707/21186778/b3902e82-c1e3-11e6-8092-74d00301865f.jpg)

![screen shot 2016-12-14 at 09 52 10](https://cloud.githubusercontent.com/assets/10982707/21186784/b773a57e-c1e3-11e6-962d-9f160f0d0342.jpg)
