### ISSUE TITLE
Don't show artist’s biography on Artwork page if the artist does not have one

### ISSUE THREAD

**Issue by sweir27** [artsy/force#444]
E.g. https://www.artsy.net/artwork/cey-adams-american-woman

![image](https://cloud.githubusercontent.com/assets/2081340/20812707/9854d6a2-b7e0-11e6-948a-5c0c75c68227.png)

**Comment by briansw** [comment]
@alloy if theres no tabs present (bio, exhibition history, etc) we should hide the module completely.

**Comment by alloy** [comment]
@briansw Filed #473 for that.
