### ISSUE TITLE
Broken formatting on GPP events

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#453]
![screen shot 2016-12-02 at 5 54 40 pm](https://cloud.githubusercontent.com/assets/1863593/20853198/7ed931c2-b8b8-11e6-8be1-501a7944d561.png)

**Comment by garrengotthardt** [comment]
@oxaudo @gnilekaw this would be also good to pick up alongside the Institutional profile page related work

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Broken formatting on GPP events when multiple are listed](https://trello.com/c/yCdpWgkU/740-broken-formatting-on-gpp-events-when-multiple-are-listed)

**Comment by gnilekaw** [comment]
@garrengotthardt I'll pick this up. What should I judge this against, ie, is there a page with correct formatting?

**Comment by gnilekaw** [comment]
@brentcas Looks like we're missing a design for when a partner has news items but doesn't have a bio. The question is, how should it look? One option would be to use the same formatting as below, but shifted to the left margin. What do you think?

Original designs: https://github.com/artsy/force-private/issues/4060

<img width="1207" alt="screen shot 2016-12-08 at 1 55 56 pm" src="https://cloud.githubusercontent.com/assets/7292475/21023345/1c04e22c-bd4e-11e6-8d9d-c3e544ece228.png">

**Comment by garrengotthardt** [comment]
I think that was the intention @gnilekaw @brentcas

**Comment by gnilekaw** [comment]
OK. Sounds straightforward. Here's how it looks in the above PR. Lmk if it should be different.

<img width="962" alt="screen shot 2016-12-08 at 3 07 51 pm" src="https://cloud.githubusercontent.com/assets/7292475/21025892/4557dcba-bd58-11e6-94df-e9749e69d48c.png">

**Comment by garrengotthardt** [comment]
👍

**Comment by garrengotthardt** [comment]
thanks @gnilekaw !
