### ISSUE TITLE
Align treatment of artworks with no titles on artwork page, artwork feeds, and GPP

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#457]
### Problem:
We're currently displaying artworks inconsistently across Force when the artwork has no title entered.

example of artwork concerned: https://cms.artsy.net/artworks/cecily-brown-14?current_partner_id=two-palms (we already fall back to "Untitled" across volt)

### Solution:
We should display the artwork title as "Untitled" across the board if there is no title entered. Existing implementations to amend include:

- [ ] On masonry grid views across artsy artworks with no title entered display as just a comma 
![screen shot 2016-12-05 at 10 27 04 am](https://cloud.githubusercontent.com/assets/1863593/20895309/e65e5a04-bae6-11e6-8bb8-449b7d0fadb5.png)

- [ ] On the artwork page currently no title displays:
![screen shot 2016-12-05 at 11 05 34 am](https://cloud.githubusercontent.com/assets/1863593/20895093/03773936-bae6-11e6-832c-6fa80a4fe7c5.png)

- [ ] On the Artwork item in an Artist's module of a GPP no title displays:
![screen shot 2016-12-05 at 11 06 20 am](https://cloud.githubusercontent.com/assets/1863593/20895120/20d98664-bae6-11e6-9056-dec3284cc4b5.png)

cc: @tayapage6 @alloy @briansw - Partner Success will take care of this one, but just putting it on your radar for future artwork modules to account for fallbacks when there isn't a title

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Align treatment of artworks with no titles on artwork page, artwork feeds, and GPP](https://trello.com/c/73mIxA97/742-align-treatment-of-artworks-with-no-titles-on-artwork-page-artwork-feeds-and-gpp)

**Comment by briansw** [comment]
@garrengotthardt would it make sense to make the change at the platform/metaphysics level so that we get the payoff across all apps without needing to update individually?

**Comment by garrengotthardt** [comment]
@briansw also thought we might want to not ever save the field as blank to gravity, but got this context from Joey - https://artsy.slack.com/archives/partner-s-help/p1480962325000100. May make sense to handle in metaphysics though

**Comment by mzikherman** [comment]
Yea, I also agree about handling it in Metaphysics. That way it'll be easier to update if/when we may want to change this behavior, which seems like it's much more UI-driven.

**Comment by alloy** [comment]
FYI There’s this existing issue in Gravity that’s related to this as well https://github.com/artsy/gravity/issues/9212.

But as @gnilekaw has noted in Slack, fixing this in MP would not fix those emails.

**Comment by gnilekaw** [comment]
@garrengotthardt, I updated this on Metaphysics. It should be fixed across the board now. 

https://staging.artsy.net/artwork/cecily-brown-14

**Comment by garrengotthardt** [comment]
awesome thanks @gnilekaw !
