### ISSUE TITLE
[Purchase] Analytics requirements

### ISSUE THREAD

**Issue by alloy** [artsy/force#463]
@1aurabrown @anipetrov Please elaborate on requirements

- [x] **Experiment Viewed**: fires when an artwork page qualified for the test is loaded with the appropriate variation params
  - properties: { 
experiment_id: purchase_flow,  
experiment_name: purchase_flow,  
variation_id: [purchase, control],  
variation_name: [purchase, control],  
nonInteraction:1  
}
- [x] **Clicked "Contact Gallery"**: fired when users clicks on the contact gallery button  
  - properties: {  
    artwork_id: artwork._id,  
    context_type: sidebar
    }  
- [x] **Clicked "Purchase"**: fired when users clicks on the purchase button  
  - properties: {  
    artwork_id: artwork._id,  
    context_type: sidebar
    }  
- [x] **Purchase request failed to submit**: fired when user clicks on the `send request` button the the /checkout page but does not successfully submit an inquiry. If we start displaying errors (state not added), we might want to gather those in a property eventually -- we do that for other "fail" events, eg. `registration_failed_to_submit` for auctions
- [x] **Clicked "Back to Browsing" purchase flow**: fires when user clicks the `Back to Browsing` button on the /thank-you page
- [x] **Sent Artwork Inquiry**: send when user _successfully_ sends an inquiry from the purchase flow
  - properties: {  
    artwork_id: artwork._id,
    artwork_slug: artwork.id,
    inquiry_id: inquiry_request.id
    user_id: user.id -> grabbed after signup
    }
- [x] **Created account**: fires when the user creates an account during the purchase flow
  - properties: {  
    context: purchase flow
    user_id: similarly, will have to force the user_id -- this is already done for the account creation events from modals  
}

**Comment by anipetrov** [comment]
is this all in staging now for me to give it another run?
