### ISSUE TITLE
Persist Purchase flow form data to cookie or session data

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/force#465]
If the user is logged out when submitting the purchase form, the page will need to be refreshed after the log in. We need to save the data they've entered into the purchase form in order to repopulate it. I am not sure the best way, but Craig sent me this change of his to look at for guidance. 

I imagine we would want to be careful not to populate a new purchase inquiry with saved data from a previous purchase inquiry on a different artwork.

**Comment by alloy** [comment]
> Craig sent me **this change** of his to look at for guidance.

@1aurabrown I’m not sure what “this change” is referring to.

**Comment by joeyAghion** [comment]
Is this perhaps missing a link to Craig's work?

In case it's helpful the API already offers a sort of support for inquiries by anonymous visitors who later log in or sign up. They can build a collector profile identified at first with an `anonymous_session_id`, then update their session with a `subsequent_user_id` after logging in or signing up. This causes any anonymous collector profile data to be copied to the authenticated profile. (The submitted inquiries are still anonymous, but this creates a link to the eventual user record.)

Just hoping this pattern points to a path forward!

**Comment by 1aurabrown** [comment]
@joeyAghion @alloy Thanks Joey, I ended using the method described, creating an anonymous user that gets linked with signed-up user on signup. I'm not entirely sure if this is necessary in this case, but this is the way it is done in the existing inquiry flow which now requires login. We aren't building a collector profile in this flow so it may not be, but we might want to do that here at some point. I was running into some issues, the details of which are not even clear to me anymore, when I was not using the same logic as the existing inquiry modal. Perhaps it's unnecessary but keeping parity with the inquiry flow seemed like the easiest solution to me.

**Comment by 1aurabrown** [comment]
Sorry, this is the link craig sent: https://github.com/artsy/force/pull/432/files#diff-1ccdcb26b0b1bc5a9ebf9c937f2c65f1R37
