### ISSUE TITLE
"More Articles" Repeats previous 3

### ISSUE THREAD

**Issue by owendodd** [artsy/force#480]
Hitting "More Articles" at the bottom of the Magazine Homepage, repeats the last 3 before showing new ones. 

![screen shot 2016-12-07 at 2 50 12 pm](https://cloud.githubusercontent.com/assets/3196536/20984019/ab9b89b2-bc8c-11e6-92bf-450750ba4a85.png)

**Comment by eessex** [comment]
@owendodd looking into this one andwondering if the "more" button's count is still supposed to be displayed on the magazine page?  The bug looks to be in this count, which is currently not displaying. 
![screen shot 2016-12-16 at 11 19 50 am](https://cloud.githubusercontent.com/assets/1497424/21269678/b263303c-c381-11e6-87d6-a7010dbcc96d.png)

**Comment by eessex** [comment]
Figured this one out -- the count is showing after the first click
