### ISSUE TITLE
Sold label missing from sold works

### ISSUE THREAD

**Issue by briansw** [artsy/force#491]
Example: https://www.artsy.net/artwork/utagawa-hiroshige-ando-hiroshige-plum-garden-at-kameido

**Comment by alloy** [comment]
@briansw What should it look like?

**Comment by briansw** [comment]
It used to be present. Should look like this: 

![screen shot 2017-01-05 at 10 46 10 am](https://cloud.githubusercontent.com/assets/1022172/21686668/349e78b0-d334-11e6-8830-e7a4a69d6dc8.png)
