### ISSUE TITLE
Remove Sign up with Twitter option

### ISSUE THREAD

**Issue by briansw** [artsy/force#499]
- **Remove** all twitter signup option on force and mg
- **Keep** all twitter sign in options on force and mg

![screen shot 2016-12-09 at 1 30 58 pm](https://cloud.githubusercontent.com/assets/1022172/21060147/ec4ddc16-be13-11e6-90b7-53e7e082066b.png)

**Comment by alloy** [comment]
@tayapage6 Why is this not ready to start?

**Comment by broskoski** [comment]
@tayapage6 bump

**Comment by dblock** [comment]
![](http://i.giphy.com/gcajW7oKirCdW.gif)

**Comment by tayapage6** [comment]
hmm don't remember moving this... yes should be ready to start cause we dont get email addresses with these signups right?
