### ISSUE TITLE
Build fails - using Production release

### ISSUE THREAD

**Issue by ksurendra** [artsy/force#5070]
Using this release https://github.com/artsy/force/releases/tag/production , build shows the blow error.
`unexpected error occurred: "https://codeload.github.com/dzucconi/geo_formatter/tar.gz/8861ae0a8efb36608a755f5be65360d4ba49ff50: Request failed \"404 Not Found\"".`

**Steps:**

1. Download https://github.com/artsy/force/releases/tag/production source
2. Run `npm i yarn -g`
3. run `yarn install`

**Stack trace:**

`Surens-MacBook-Pro:force-production suren$ yarn install
yarn install v1.19.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "superagent@3.8.3" is incompatible with requested version "superagent@^1.2.0"
warning Resolution field "superagent@3.8.3" is incompatible with requested version "superagent@^1.2.0"
warning Resolution field "moment@2.22.2" is incompatible with requested version "moment@~2.4.0"
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.26.3"
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.0.0"
warning Resolution field "babel-core@7.0.0-bridge.0" is incompatible with requested version "babel-core@^6.0.0"
warning Resolution field "superagent@3.8.3" is incompatible with requested version "superagent@^2.0.0"
[3/5] 🚚  Fetching packages...
warning Pattern ["react-relay@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.5/react-relay-1.5.0-artsy.5.tgz","react-relay@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.3/react-relay-1.5.0-artsy.3.tgz"] is trying to unpack in the same destination "/Users/suren/Library/Caches/Yarn/v5/npm-react-relay-1.5.0-artsy.5-956280da8d941af7f6f65f3831b01051ee2c32c7/node_modules/react-relay" as pattern ["react-relay@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.5/react-relay-1.5.0-artsy.5.tgz"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["relay-runtime@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.5/relay-runtime-1.5.0-artsy.5.tgz","relay-runtime@1.5.0-artsy.5","relay-runtime@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.3/relay-runtime-1.5.0-artsy.3.tgz","relay-runtime@1.5.0-artsy.5","relay-runtime@1.5.0-artsy.5"] is trying to unpack in the same destination "/Users/suren/Library/Caches/Yarn/v5/npm-relay-runtime-1.5.0-artsy.5-6f24fa3cd7dcfc58164ee1b21b059c535e6419bf/node_modules/relay-runtime" as pattern ["relay-runtime@https://github.com/artsy/relay/releases/download/v1.5.0-artsy.5/relay-runtime-1.5.0-artsy.5.tgz","relay-runtime@1.5.0-artsy.5"]. This could result in non-deterministic behavior, skipping.
[##################################---------------------------------------------------------------------------------------------------------------------------] 460/214[[error An unexpected error occurred: "https://codeload.github.com/dzucconi/geo_formatter/tar.gz/8861ae0a8efb36608a755f5be65360d4ba49ff50: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/suren/Personal/Projects/research/force-production/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by damassi** [comment]
You'll want to pull from master.
