### ISSUE TITLE
Underline inconsistency

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#51]
@owendodd commented on [Wed Apr 13 2016](https://github.com/artsy/force-private/issues/4820)

General underline inconsistency for artist follows (https://www.artsy.net/article/halley-johnson-e-a-moc)

![screen shot 2016-04-11 at 4 14 41 pm](https://cloud.githubusercontent.com/assets/3196536/14441001/a3e7e718-0000-11e6-9979-c6a38fdf1248.png)
![screen shot 2016-04-11 at 4 14 47 pm](https://cloud.githubusercontent.com/assets/3196536/14441000/a3e4c5ce-0000-11e6-9dab-bf0d222c0e9d.png)

**Comment by eessex** [comment]
Couldn't find any examples of inconsistency, as far as I can tell this has been fixed.
