### ISSUE TITLE
[Purchase Request] Sporadic 400 error

### ISSUE THREAD

**Issue by briansw** [artsy/force#538]
```
{:error=>"405 Not Allowed", "X-Frame-Options"=>"DENY", "X-Robots-Tag"=>"noindex", "Allow"=>"OPTIONS, POST"}
```

![screen shot 2016-12-13 at 2 16 00 pm](https://cloud.githubusercontent.com/assets/1022172/21155066/b11a9b56-c13e-11e6-9a46-49a0eba4f560.png)

**Comment by 1aurabrown** [comment]
@briansw i believe this has been fixed, let me know if you see it again!

**Comment by briansw** [comment]
I got the error again:

```
{:error=>"405 Not Allowed", "X-Frame-Options"=>"DENY", "X-Robots-Tag"=>"noindex", "Allow"=>"OPTIONS, POST"}
```

![screen shot 2016-12-15 at 2 25 47 pm](https://cloud.githubusercontent.com/assets/1022172/21238797/62ac7058-c2d2-11e6-9141-51828c87129b.png)

**Comment by tayapage6** [comment]
We need to update our NR plan.

**Comment by 1aurabrown** [comment]
@tayapage6 what is NR?
