### ISSUE TITLE
[EOY] Artist page SEO banner

### ISSUE THREAD

**Issue by broskoski** [artsy/force#539]
The existing “this work is in an ongoing auction” banner is rendered server-side and I would also prefer not to have to pull down the full JSON file of featured artists on each client.

- Cache the JSON data per server process.
- If the artist is in the JSON data, render a SEO banner instead of an auction one [here](https://github.com/artsy/force/blob/dacb41a7c51bc2085b97150b811bb17e7e01970c/apps/artist/routes.coffee#L38).
- Remove the ‘edit JSON page’ route so that people can’t easily change the contents and have it go out of date with what’s cached on the server

**Comment by alloy** [comment]
@broskoski Can you share the S3 URL?

**Comment by broskoski** [comment]
You'll want to use the data endpoint directly (i.e. once its deployed http://www.artsy.net/eoy_2016/data )

**Comment by alloy** [comment]
Ahhh, gotcha 👍

**Comment by alloy** [comment]
@briansw What is the thumbnail image of, the EOY article? And, if so, do you know of a URL where it exists?

<img width="379" alt="screen shot 2016-12-20 at 20 40 38" src="https://cloud.githubusercontent.com/assets/2320/21374417/ab15e2b8-c6f4-11e6-9925-e46ecbdc819b.png">

**Comment by briansw** [comment]
@alloy here you go: https://cl.ly/0u0n262n2N3j

**Comment by alloy** [comment]
Currently I’m making the banner look exactly like auction banners (re-using the code/styling). Do you have a strong opinion about the styling being different (all black text) and the order of the heading/details line?

<img width="387" alt="screen shot 2016-12-20 at 21 46 17" src="https://cloud.githubusercontent.com/assets/2320/21375765/f28ea2b6-c6fd-11e6-9f3b-686c76cb2a17.png">

**Comment by briansw** [comment]
That's fine. I put the EOY series name at the bottom since the most
influential/top emerging etc feel more important and if we keep the bottom
line gray it might be worth swapping places.

**Comment by alloy** [comment]
Gotcha, makes sense, I’ll swap those.
