### ISSUE TITLE
/Institutions page refactor

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#548]
- [ ] Keep institutions eligible for carousels the same, however update the design to reflect not having shows called out, but rather just the institution name. Design reference for /galleries is included above above. The same design would be used on /institutions just with copy being "Featured Institution"

![screen_shot_2016-12-08_at_9 15 57_am](https://cloud.githubusercontent.com/assets/796573/23634769/06f2ff18-029a-11e7-99e3-e7cfb3170251.png)

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [/Institutions logic overview for refactor](https://trello.com/c/Ymto8TZJ/750-institutions-logic-overview-for-refactor)

**Comment by gnilekaw** [comment]
@starsirius Think we can close this one?

**Comment by starsirius** [comment]
I think there is still one todo in the trello card. Updated this issue description to match that.
