### ISSUE TITLE
Redirect of artwork by ID to artwork by slug

### ISSUE THREAD

**Issue by dblock** [artsy/force#5519]
Both pages work, http://artsy.net/artwork/516dfb9ab31e2b2270000c45 and https://www.artsy.net/artwork/william-michael-harnett-the-old-violin. 

This is not good for Google as it's the same resource. The first one should 301 or 302 redirect to the other.

**Comment by zephraph** [comment]
Thanks for reporting @dblock!

We should definitely update to have a redirect there. Ultimately, I don't _think_ it's actually a big deal for SEO though. The id version of the URL isn't in the sitemap and isn't expressed via links on the site. The only time I guess it'd become an issue is if we had backlinks that were using ids, but even then it'd really only be an issue if there was a lot of domain authority or a lot of links. 

Still, a good catch! Will move this to a Jira ticket.
