### ISSUE TITLE
Disable purchase requests for galleries with pre-qualification enabled

### ISSUE THREAD

**Issue by briansw** [artsy/force#577]
Example: https://www.artsy.net/artwork/damien-hirst-norleucine-2

**Comment by 1aurabrown** [comment]
this was fixed by https://github.com/artsy/metaphysics/pull/501, maybe it wasn't deployed yet at the time.

![screen shot 2016-12-19 at 3 38 52 pm](https://cloud.githubusercontent.com/assets/3171662/21316534/74b25f56-c601-11e6-9f73-f567f38c184c.png)
