### ISSUE TITLE
Works for you bell shouldn't be on checkout page

### ISSUE THREAD

**Issue by briansw** [artsy/force#578]
It just started appearing today. Previously, it wasn't there which was correct.

![screen shot 2016-12-16 at 8 57 05 am](https://cloud.githubusercontent.com/assets/1022172/21265098/b6836ac4-c36d-11e6-81a9-fea418d27fcb.png)

**Comment by 1aurabrown** [comment]
@briansw said he wants this to be the same style as the fair header, which includes a user menu dropdown on the right and is currently not reusable, and if done right would be extracted into something both fairs and the purchase flow can use. he said to punt on this until we see the results of the test.
