### ISSUE TITLE
[Purchase Request] Art Basel in Miami Beach checkbox still relevant?

### ISSUE THREAD

**Issue by alloy** [artsy/force#592]
@briansw We show this checkbox on the purchase request form, but afaik that fair is already over, so should we remove it again?

<img width="294" alt="screen shot 2016-12-19 at 13 45 09" src="https://cloud.githubusercontent.com/assets/2320/21324824/63ac332c-c5f1-11e6-8340-0b10b6b74869.png">

**Comment by briansw** [comment]
The checkbox should show up for any work that's part of a fair, not just Miami Beach.

**Comment by alloy** [comment]
I was specifically referring to the future tense being used in that copy, while this fair is already closed.

However, this brings up an interesting point, because for e.g. [this work](https://staging.artsy.net/artwork/jeffrey-cheung-pairs?microsite=1&profile_id=miami-project-2016&fair_id=miami-project-2016&fair_name=Miami%20Project%202016) no checkbox shows up, whereas I understand from you that you would have expected a checkbox with the copy: “I will attend Miami Project 2016” ?

**Comment by briansw** [comment]
That's something we should take care of across the board. We keep inquiries open for about 2 weeks after the fair closes and those checkboxes persist for that window. We could make it say "attended" in those instances. I'm not sure what the checkbox does in volt though. If you'd like to remove it instead of change tense, it would be best to check with @stasya and Morgan.

**Comment by stasya** [comment]
@briansw thanks for looping me in; yes, if we are able to switch to "attended" on works between the end date of the fairs and the end of the 2 week period, that would be great; and just to confirm, the box is removed altogether 2 weeks after the fair ends?

**Comment by briansw** [comment]
@stasya that's right.

**Comment by tayapage6** [comment]
@alloy include the work link

**Comment by alloy** [comment]
@1aurabrown This is the work I used https://m-staging.artsy.net/artwork/damien-hirst-norleucine-2, but weirdly enough it now seems to say "contact for price".

Also, this fair did actually close on the 4th, so I should have been able to see that checkbox yesterday.
