### ISSUE TITLE
[Purchase Request] User validation errors from Gravity are not handled gracefully.

### ISSUE THREAD

**Issue by alloy** [artsy/force#593]
When trying to create a new user, client-side validation is performed to ensure that fields aren’t left blank and the password isn’t too short. However, we don’t handle validation errors that come back from Gravity.

E.g. try signing-up with an email address like `foo@bar`. This passes the client-side validation, but `https://stagingapi.artsy.net/api/v1/me/anonymous_session` responds with a `400` and the following JSON: `{"type":"param_error","message":"Email is invalid.","detail":{"email":["is invalid"]}}`.

Once this happens, the ‘SEND REQUEST’ button remains in the spinning state and can’t be used again. Effectively meaning that users have to reload the page and fill out all the information again.

Maybe API validation error parsing is out of scope, but setting the button back to the initial state should probably be done on _any_ error.

**Comment by 1aurabrown** [comment]
we also have this component, which could be useful: https://github.com/artsy/force/blob/dacb41a7c51bc2085b97150b811bb17e7e01970c/components/mailcheck/readme.md
