### ISSUE TITLE
Modifying initial message in Contact Gallery doesn't change message in modal

### ISSUE THREAD

**Issue by ashkan18** [artsy/force#598]
# Problem
When user modifies default message in Contact Gallery section, it does NOT update the default message in sending inquiry modal. In the following screenshot, notice the message outside of the modal `Hello! One message` is different than what modal was pre-populated with.

![screen shot 2016-12-20 at 12 03 28 pm](https://cloud.githubusercontent.com/assets/1230819/21360113/9cb95cec-c6ac-11e6-9ecf-bfbaa1c4fe3b.png)

**Comment by 1aurabrown** [comment]
It seems likely that I introduced this bug since I made some changes to that area for the purchase flow.
