### ISSUE TITLE
Video unit height in EOY feature

### ISSUE THREAD

**Issue by owendodd** [artsy/force#606]
the videos all seem to have tons of space around them for some reason. (in safari)

![screen shot 2016-12-20 at 3 53 38 pm](https://cloud.githubusercontent.com/assets/3196536/21371406/77ec3eda-c6ce-11e6-8b77-6b05341e209c.png)
![screen shot 2016-12-20 at 3 53 44 pm](https://cloud.githubusercontent.com/assets/3196536/21371407/78086de4-c6ce-11e6-9e63-77f9b025ee74.png)
![screen shot 2016-12-20 at 3 54 07 pm](https://cloud.githubusercontent.com/assets/3196536/21371408/7809a7cc-c6ce-11e6-99db-9d16940bc134.png)

**Comment by eessex** [comment]
Hmm looking into this now.  Seems to be fine in other browsers.
