### ISSUE TITLE
Artist Module Updates

### ISSUE THREAD

**Issue by broskoski** [artsy/force#61]
_From @briansw on May 19, 2016 15:10_

#### Launch as Lab feature first for review

![artist-module 1x](https://cloud.githubusercontent.com/assets/1022172/15520596/2b3a2442-21d5-11e6-9066-b754d06da05b.jpg)

_Copied from original issue: artsy/force-private#5044_

**Comment by broskoski** [comment]
_From @artsyit on July 26, 2016 14:24_

<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;7N2fO8zF&#x2F;358-artwork-page-artist-module-updates"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Artwork page: Artist module updates</a>

**Comment by broskoski** [comment]
_From @briansw on August 23, 2016 15:18_

#### General
- [ ] Tab and header titles need to be adjusted based on rule above "Highlights" vs "History"
- [ ] When no exhibition history/highlights are present on the bio tab, don't collapse the bio
- [ ] Make CV button the small-button style
- [ ] Make the View all articles button small-button style
- [ ] There should be 20px between article title and byline

#### Artists with 15 or Fewer Shows
- [ ] Should look like no. 1: https://www.artsy.net/artwork/cosima-von-bonin-george
- [ ] Should look like no. 2: https://www.artsy.net/artwork/michael-krebber-untitled-3
- [ ] Should look like no. 3: https://www.artsy.net/artwork/nick-veasey-superman-3

#### Artists with 16 or More Shows
- [ ] Should look like no. 1: https://www.artsy.net/artwork/andy-warhol-details-of-renaissance-paintings-sandro-botticelli-birth-of-venus-1482-4
- [ ] Should look like no. 2: https://www.artsy.net/artwork/simon-fujiwara-ich-cornerboy-double-32l-1
- [ ] Should look like no. 3: Can't find an example, but maybe with terminal you can find one quicker than me.

**Comment by briansw** [comment]
- [ ] I just noticed that the exhibition sequence seems to be out of order as well. The shows should be listed newest to oldest.

**Comment by xtina-starr** [comment]
@briansw after talking with @mzikherman, it looks like these are already sorted by date in addition to a specific weight.

**Comment by briansw** [comment]
Right, I think the weighting is correct, but the sort is incorrect for the display on the page. Ie, it's correct that we're pulling older shows from 2014, but the shows that are displayable should show up in reverse chronological order.

**Comment by xtina-starr** [comment]
They are ordered by date, but weighted. Wouldn't reordering it again disrupt the order of the weight?

**Comment by briansw** [comment]
The weighting should be considered only when making the initial selection of displayable shows and then that group should be sorted by date.
