### ISSUE TITLE
Max Width for Article grid

### ISSUE THREAD

**Issue by owendodd** [artsy/force#628]
Max-width of 1600px,

This should apply to the header as well. 

![screen shot 2017-01-02 at 1 10 38 pm](https://cloud.githubusercontent.com/assets/3196536/21594143/09fa17e8-d0ed-11e6-8166-21365c447255.png)

**Comment by eessex** [comment]
Should we update the footer menu to do these widths as well?
![screen shot 2017-01-05 at 11 53 58 am](https://cloud.githubusercontent.com/assets/1497424/21689224/b6c34a4c-d33d-11e6-95c4-976c7ba8a7f9.png)

**Comment by owendodd** [comment]
Yeah I think that makes sense!
