### ISSUE TITLE
"Bid now" buttons now saying "Contact Seller"

### ISSUE THREAD

**Issue by briansw** [artsy/force#63]
_From @briansw on June 10, 2016 14:48_

Was working previously, something must have been reverted by accident.

![screen shot 2016-06-10 at 10 47 39 am](https://cloud.githubusercontent.com/assets/1022172/15968153/c8506252-2ef8-11e6-9ee4-8ae5da4d43ef.png)

fyi @katarinabatina 

_Copied from original issue: artsy/force-private#5203_

**Comment by alloy** [comment]
Seems fixed.
