### ISSUE TITLE
Related Works repeats works with multiple artists

### ISSUE THREAD

**Issue by eessex** [artsy/force#632]
Artworks in related works bar are printed once for each artist attributed to it. 

![screen shot 2017-01-04 at 11 07 50 am](https://cloud.githubusercontent.com/assets/1497424/21649055/533da71c-d26e-11e6-9a99-506222dea328.png)

**Comment by alloy** [comment]
This is the artwork in the example https://www.artsy.net/artwork/david-salle-exquisite-corpse-12, it seems very specific to this artwork.

**Comment by 1aurabrown** [comment]
I think that the place to fix this is on metaphysics or even gravity -- why is the same work being returned more than once in the same response from the API, in the first place?

**Comment by cavvia** [comment]
I think this actually needs to be fixed in the elasticsearch query we send from gravity - it's aggregating by artist but might not be enforcing unique artwork IDs within that aggregation. I can have a look at it.

**Comment by 1aurabrown** [comment]
alright i'm going to close this in favor of the new issue i made
