### ISSUE TITLE
New full-screen signup form

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#635]
Larger issue: https://github.com/artsy/collector-experience/issues/34

Allow signup via email/password and w/ Facebook, including regular 'Log In' modal case.

Include truncated 'feed' of artists/artworks.

Questions:

Is this truncated 'feed' supposed to be dynamic?
How's the second artist derived?
How to determine the new works count? What if there are no new works today?

<img width="1090" alt="screen shot 2017-01-04 at 2 00 35 pm" src="https://cloud.githubusercontent.com/assets/1457859/21655082/7e0161a6-d286-11e6-9331-877c5624eaf3.png">

**Comment by alloy** [comment]
Implemented by #655
