### ISSUE TITLE
CV formatting issues in Safari

### ISSUE THREAD

**Issue by briansw** [artsy/force#65]
_From @briansw on August 8, 2016 15:14_
- https://www.artsy.net/artist/jonathan-cross
- https://www.artsy.net/artist/markus-schinwald

![screen shot 2016-08-08 at 11 14 34 am](https://cloud.githubusercontent.com/assets/1022172/17484706/2b899044-5d59-11e6-9f93-4cefe5ac87e6.png)
![screen shot 2016-08-08 at 11 16 05 am](https://cloud.githubusercontent.com/assets/1022172/17484707/2b9d18e4-5d59-11e6-81d6-cef9a4c7fa52.png)

_Copied from original issue: artsy/force-private#5448_

**Comment by broskoski** [comment]
Can't replicate this! Is this still an issue @briansw ?

**Comment by briansw** [comment]
Yeah, not seeing it at the moment...
