### ISSUE TITLE
Make caret on new Artist Page CTA white/transparent

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#657]
Right now I just borrowed the existing one, but to actually make it white with a different colored border, it seems like you need two div overlays with differing borders? Rather than just the one that accomplishes the solid color caret.

Should look like:

<img width="276" alt="screen shot 2017-01-06 at 10 48 48 am" src="https://cloud.githubusercontent.com/assets/1457859/21723246/bc1ac144-d3fd-11e6-9925-d53631c40857.png">

Currently looks like:

<img width="278" alt="screen shot 2017-01-06 at 10 49 11 am" src="https://cloud.githubusercontent.com/assets/1457859/21723256/c63b0134-d3fd-11e6-9575-1a6a6df91c5d.png">

**Comment by mzikherman** [comment]
Actually, maybe this is a great easy one for @l2succes to get started on! (if you haven't already @xtina-starr ).

**Comment by xtina-starr** [comment]
Feel free to go for it @l2succes!
