### ISSUE TITLE
Partner artist bio blurb not displayed properly

### ISSUE THREAD

**Issue by starsirius** [artsy/force#673]
Re: https://artsy.slack.com/archives/partner-s-help/p1484006740001128

Still need to confirm but looks like the [blurb](https://github.com/artsy/force/blob/77fd88b34b4b096a11d074631055f0332db3cd18/apps/partner2/client/artists_artist.coffee#L94) (that uses dotdotdot) doesn't display the multi-paragraph content when it is fewer than 4 lines.

**Comment by gnilekaw** [comment]
This cropped up again. https://artsy.slack.com/archives/partner-s-help/p1484770312001570

**Comment by jonallured** [comment]
This was reported again: https://artsy.slack.com/archives/partner-s-help/p1486138878003209

I ended up just editing the bio to make it not trigger the bug. I removed one newline and that was enough to get it to behave. The original, busted bio:

```
(b.1974 in Cracow) was educated at the Cracow’s Academy of Fine Arts (1995-2000). 
2003-2009 he vied and worked in Florence 
2009- 2012 he lives and works in Cracow, by 2009  employed on Academy of Fine Arts in Cracow 
His works have been purchased by the Frissiras Museum in Athen,  and appear in  private collections. 
He was selected for shortlist  for „100 Painters of Tomorrow” – orgenised by Thames&Hudson and Beers. Lambert.
```
