### ISSUE TITLE
[v1.5] Categories aren't reliably grayed out when 0 results

### ISSUE THREAD

**Issue by briansw** [artsy/force#68]
_From @briansw on May 25, 2016 13:19_

https://www.artsy.net/collect?medium=sculpture&partner_cities%5B0%5D=Denver%2C%20CO%2C%20USA
- Found & Common Materials has 0 results once clicked

![screen shot 2016-05-25 at 9 18 41 am](https://cloud.githubusercontent.com/assets/1022172/15541270/bf9c037e-2259-11e6-9585-a4a6ddda28aa.png)

_Copied from original issue: artsy/force-private#5101_

**Comment by alloy** [comment]
Appears fixed.
