### ISSUE TITLE
Signup QA

### ISSUE THREAD

**Issue by briansw** [artsy/force#688]
## Bumper
- [x] Text should be updated per issue
- [x] Bumper should animate in
## Takeover
- [x] Auto triggers aren't happening yet
- [x] Text should be updated per issue
- [x] When animating up, the content should fade in simultaneously and the main site content opacity should decrease
- [x] Content should be centered vertically and horizontally on page
- [x] Put focus on name field when takeover is triggered
- [x] Form fields too wide (should be 340px)
- [x] Works for you dropdown should be wider (340px)
- [x] Margin between forms and dropdown should be tighter (30px)
- [x] Works for you should be 15px, bell size should be bigger
- [x] Edges of dropdown should fade out at bottom with content
- [x] dropdown box-shadow: 0 0 20px 0 rgba(0,0,0,.1)
- [x] “OR” divider lines should be #e5e5e5
- [x] Terms of use text should be 13px with a line-height set so the underline isn't hugging the baseline of the text. Decrease space between button and text.
- [x] Already have an account? Log in. Don’t allcap log in, add period.
- [x] Shouldn’t get a cursor:pointer on the dropdown
- [x] Need to confirm continue with facebook works — I don’t have an acct to try with.
## Payoff
- [x] Text should be updated per issue
- [x] Sub text should be 20px
- [x] Add more spacing between sub text and search bar
- [x] Content should be centered horizontally and vertically
- [x] Done button should be smaller with space between dropdown and button
- [x] Focus should be put on the search field immediately
- [x] Don’t show artists the user is following in subsequent recommendations.

**Comment by alloy** [comment]
Not sure if this has already been done, otherwise it should be included https://github.com/artsy/force/issues/660

**Comment by 1aurabrown** [comment]
@xtina-starr not sure if you've started on this, but we can split it?

**Comment by xtina-starr** [comment]
@1aurabrown I haven't. I'm up for splitting it.

**Comment by 1aurabrown** [comment]
@xtina-starr alright i'm going to dig in. when you're ready to start on it we can break it down, until then i'll just pick some random items.

**Comment by mzikherman** [comment]
@briansw what do you mean by 'Auto triggers aren't happening yet' ?

**Comment by briansw** [comment]
@mzikherman the takeover should trigger based on:
- scrolling
- clicking follow button below artist name
- clicking sign up

**Comment by mzikherman** [comment]
Ah got it. Yea, the scrolling one is happening, but not the other two.

**Comment by mzikherman** [comment]
@briansw re: 

> Don’t show artists the user is following in subsequent recommendations.

You shouldn't be getting any. It uses the same API that powers this on the homepage, so it should be filtering out any artists that you already follow. It does seem to work for me, eventually I exhaust all available suggestions. Were you seeing differently/can repro?

**Comment by briansw** [comment]
Yes, I got recommended the artist I just followed immediately upon landing. I also got recommended the same artist after following in the dropdown.

**Comment by mzikherman** [comment]
Interesting, do you remember which artist it was? I've never seen that, and looking at the API, it doesn't seem to allow for that either.

For instance, the recommendations are based on the artist you started with, so it wouldn't show up in the initial 4. However, it might show up as a rec based on something you then click, since you aren't actually following the first artist yet- I can fix that.

Maybe I'll put in that fix, which I believe could lead the initial artist to come up at some point after the initial 4 you'd get, and we can just watch for it later?

**Comment by briansw** [comment]
I believe it happened both times I tried once was with Cosima von Bonin. I don't remember the other artist unfortunately.
