### ISSUE TITLE
Consign message margins off for multiple artists

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#695]
Looks a bit funky on this page: https://www.artsy.net/artwork/david-salle-exquisite-corpse-12

![image](https://cloud.githubusercontent.com/assets/2236794/21870537/dafb33d8-d82a-11e6-9467-e7f753b2f32f.png)

Sorry if the labelling is wrong -- wasn't sure if its auctions or coEx

**Comment by alloy** [comment]
@acjay Is this something your team can take on?

**Comment by acjay** [comment]
Issue moved to [artsy/auctions #292](https://github.com/artsy/auctions/issues/292) via [**ZenHub**](https://www.zenhub.com/)
