### ISSUE TITLE
Clicking 'Bid' and signing up with social takes you to personalize and homepage

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#696]
...instead of skipping onboarding and going back to the bid screen.

Essentially it wasn't honoring any `redirectTo` option, even though it should.

The 'quick' fix for now is https://github.com/artsy/artsy-passport/pull/89 , just to specify `skip-onboarding=true` in the query params as well. The regression stemmed from a larger refactor in the passport library, so this is just the quick fix for now.

**Comment by alloy** [comment]
@acjay ping

**Comment by acjay** [comment]
Issue moved to [artsy/auctions #293](https://github.com/artsy/auctions/issues/293) via [**ZenHub**](https://www.zenhub.com/)
