### ISSUE TITLE
Padding inconsistency

### ISSUE THREAD

**Issue by notrueblood** [artsy/force#7174]
There is a horizontal padding inconsistency in page footers. For example, the [auction page](https://www.artsy.net/auction/seoul-auction-spring-sale) footer has no horizontal padding, but the [artwork page](https://www.artsy.net/artwork/lee-ufan-untitled-2034) footer has horizontal padding consistent with the rest of the page.

#### Artwork page with horizontal padding
<img width="360" alt="Artwork page with horizontal padding" src="https://user-images.githubusercontent.com/40576412/111697250-b6edfd00-880b-11eb-9683-fe1f45edf8e6.png">

#### Auction page without horizontal padding
<img width="361" alt="Auction page without horizontal padding" src="https://user-images.githubusercontent.com/40576412/111697342-d1c07180-880b-11eb-9920-8af92be5756c.png">

Happy to open a PR to fix this if others find the problem warrants one. Otherwise, feel free to close this issue.

**Comment by damassi** [comment]
Thanks for filing this issue! There's a divide between our old code and new code in the app, where /artwork is new and /auction is old, and on a slightly different stack. We recently did some work on the footer so perhaps this was missed. Will give it a look 👍

**Comment by damassi** [comment]
Added to JIRA - ty for the report.
