### ISSUE TITLE
Nested urls on fair articles 

### ISSUE THREAD

**Issue by kanaabe** [artsy/force#718]
A fair article like

https://www.artsy.net/article/london-art-fair-artists-announced-for-photo50-at-london-art-fair-2017

should be 

https://www.artsy.net/london-art-fair/article/london-art-fair-artists-announced-for-photo50-at-london-art-fair-2017

much like partner-written articles

**Comment by eessex** [comment]
@kanaabe, does it seem correct to use the 'fair_ids' column to find these?

**Comment by kanaabe** [comment]
You can reference: https://github.com/artsy/microgravity/pull/96/commits/521c041578656e9c8aa95d6c1a9008629ee815be#diff-1be63e5e28d2c42ad1766d25f40a770dR47

Basically it needs to be written by the fair channel and associated to a fair (via `fair_ids`).
