### ISSUE TITLE
Artworks in auction missing information on artist page

### ISSUE THREAD

**Issue by devangt** [artsy/force#729]
![image](https://cloud.githubusercontent.com/assets/753098/22179146/e6231b86-e018-11e6-963a-daaf24cec969.png)

Artwork should have

- [x] Estimate and bid link if no bids yet
- [x] Current bid price and number of bids if at least one bid has been made
- [x] Bid now link

cc @tayapage6 @katarinabatina

**Comment by tayapage6** [comment]
@devangt propose to just fix the regression bug (so we used to have current price and #bids, right?) and keep the days left in auction as a new feature to be considered with all artwork merchandizing efforts in https://github.com/artsy/collector-experience/issues/97

@katarinabatina or @briansw do you have a screenshot of how this used to look?

**Comment by briansw** [comment]
@tayapage6 this is what we had previously designed:

![artwork-bid](https://cloud.githubusercontent.com/assets/1022172/22223099/93348caa-e187-11e6-8654-acf00c88b309.jpg)

**Comment by katarinabatina** [comment]
hi just clarified with @devangt we've never had support for this, we tried to squeeze it in when @briansw was looking at artwork metadata a few months back but getting in timely increment data about the artwork is a larger work item. The auctions team will likely take this on in our next sprint.

**Comment by devangt** [comment]
Thx @katarinabatina my bad for thinking this was a regression. Lets def. discuss in tomorrow sprint kickoff.

**Comment by 1aurabrown** [comment]
@katarinabatina i can take this if it is something we want to do now. i will assign myself. just let me know tomorrow whether or not this item is really "Ready to Start"

**Comment by katarinabatina** [comment]
@1aurabrown if this is one you can pick up then awesome, here is an adjusted spec that removes the lot number and shows what should happen if there are no current bids on a lot. 

![image](https://cloud.githubusercontent.com/assets/6482926/22250321/744e4c3a-e214-11e6-9802-17a935cf4656.png)
![image](https://cloud.githubusercontent.com/assets/6482926/22250327/7ac1c1fa-e214-11e6-88f2-ded063855953.png)

**Comment by mzikherman** [comment]
@katarinabatina should there still be a 'Bid Now' link under the bid information? Noticed that it's missing in the first two images in your comp, where it still might make sense to link to the bid page/artwork page?

**Comment by 1aurabrown** [comment]
@mzikherman it does still link to the artwork page, i just took out the underline as per her image

**Comment by katarinabatina** [comment]
@mzikherman yes we've removed the underline but clicking on the link should send the user to the artwork page.

**Comment by mzikherman** [comment]
Got it 👍
