### ISSUE TITLE
Other Works by Artist Update

### ISSUE THREAD

**Issue by briansw** [artsy/force#73]
_From @briansw on July 6, 2016 18:30_
#### Launch as Lab feature first for review

---

We'd like to break up the "Other Works by [Artist]" Module into two modules:
- [Medium] by Artist – Medium chosen should match the medium of the artwork user is currently viewing, display 10 inquireable works
- Other Works by [Artist] – Ideally, this excludes the works found in the medium module, display 10 inquireable works

Don't break into two modules when:
- The work the user is viewing is the only instance of that medium by the artist
- Artist has 10 or fewer inquireable works
- All of the artist's works are the same medium

---

![otherworks](https://cloud.githubusercontent.com/assets/1022172/16629968/2c840214-4386-11e6-8995-a39b4fd3d9cd.jpg)

_Copied from original issue: artsy/force-private#5326_

**Comment by alloy** [comment]
This is done.

**Comment by briansw** [comment]
@alloy this hasn't been worked on yet. This ticket is about displaying a module of works in the same medium as the one the user is currently looking at. We currently only display an array of available works by the artist without taking medium into account.

**Comment by alloy** [comment]
@briansw Thanks for being sharp! 🙌

**Comment by xtina-starr** [comment]
@tayapage6 @alloy since this is something that remains to be done should I wait for it to be prioritized or just pick it up when I'm ready for a new ticket?

**Comment by alloy** [comment]
@xtina-starr Do you have a feeling for the scope of the required work?

**Comment by xtina-starr** [comment]
@alloy not entirely. I believe majority of the work would be metaphysics.

**Comment by alloy** [comment]
Let’s wait for it to become prioritised then.
