### ISSUE TITLE
A/B Test: Banner Update

### ISSUE THREAD

**Issue by briansw** [artsy/force#75]
_From @briansw on July 7, 2016 21:25_
#### Launch as Lab feature first for review

Banners already display and hide themselves correctly. The three updates here include:
- Style changes to banner
- Adding lateral navigation

Todo
- [ ] Show banner
- [ ] Show lateral nav
- [ ] Fair banner
- [ ] Fair lateral nav
- [ ] Auction banner
- [ ] Auction lateral nav

When setting up the A/B test, put all admin accounts in the test group.

---

![banner-update](https://cloud.githubusercontent.com/assets/1022172/16670189/10e1b1fa-4467-11e6-8219-8435bbd3f7d1.jpg)

_Copied from original issue: artsy/force-private#5341_

**Comment by briansw** [comment]
_From @artsyit on July 26, 2016 14:22_

<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bDy0xJcB&#x2F;357-artwork-page-banner-nav"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Artwork page: Banner Nav</a>

**Comment by alloy** [comment]
@tayapage6 This one is probably for you to figure out if we still want to do this.

**Comment by briansw** [comment]
@tayapage6 also happy to walk you through the featureset and background info around this project.
