### ISSUE TITLE
[Artist Signup CTA] Event banner masks sign-up button

### ISSUE THREAD

**Issue by alloy** [artsy/force#750]
![screen shot 2017-01-24 at 14 52 27](https://cloud.githubusercontent.com/assets/2320/22264111/dccacfe2-e244-11e6-9dbe-108bf82c1376.png)

**Comment by mzikherman** [comment]
I vote for...keeping as-is OR removing/hiding the auction pop-up entirely?

**Comment by tayapage6** [comment]
I think the UX is pretty bad with the banner. Would vote for removing any popup banners on this page... @briansw seems like we need to find a new home for banners if we want to do more lower right hand corner CTAs...?

**Comment by briansw** [comment]
My vote would be to remove from artist pages as well. We've done this in a couple other places. I think we're reaching a point where auctions are happening so frequently that we should try to get rid of them entirely or possibly only show on the home page.
