### ISSUE TITLE
[Artist Signup CTA] Infinite scroll continues to work while modal CTA is up.

### ISSUE THREAD

**Issue by alloy** [artsy/force#753]
This might cause the user to miss some works, leaves them in a different state than when they entered the modal, and is just slightly weird.

![infinite-scroll-in-modal](https://cloud.githubusercontent.com/assets/2320/22264515/3a1b5fda-e246-11e6-87cf-973a2cc4f6d1.gif)

**Comment by alloy** [comment]
@broskoski said:

> oh yeah you gotta make the page behind `position:fixed` and `overflow:hidden`

**Comment by mzikherman** [comment]
good call!
