### ISSUE TITLE
[Artist CTA Signup] Notification count on bell and fake list don’t add up

### ISSUE THREAD

**Issue by alloy** [artsy/force#755]
In this example we could just show ‘10’ on the bell.

![screen shot 2017-01-24 at 15 07 51](https://cloud.githubusercontent.com/assets/2320/22264740/0a10b154-e247-11e6-828e-a4f51cdeab04.png)

**Comment by mzikherman** [comment]
I think the '3' represents distinct 'bundles', like a new set of warhol works, a new set of rosenquist....and presumably a third one in the faded out section.

So the '3' makes sense in that interpretation.

**Comment by alloy** [comment]
Maybe, but I don’t think the user can understand that at this point, they might make the connection between the two things better if they see the two add up.

**Comment by mzikherman** [comment]
That is the way the existing notifications bell works (it's the count of 'bundles').

I sort of think we should leave it (and close this w/o doing anything), but I'm not super opinionated. @briansw ?

**Comment by 1aurabrown** [comment]
in this mocked ui should it perhaps say 2, since it looks as though there are 2 bundles?
