### ISSUE TITLE
[Artist Signup CTA] Duplicate suggestions in artist payoff screen

### ISSUE THREAD

**Issue by alloy** [artsy/force#756]
![screen shot 2017-01-24 at 15 12 19](https://cloud.githubusercontent.com/assets/2320/22264862/96033cc2-e247-11e6-9e70-ca0ee63b8706.png)

**Comment by mzikherman** [comment]
I think this is a dupe of https://github.com/artsy/force/issues/752

**Comment by alloy** [comment]
Oops, yeah. Although I’m gonna close the other one, as it doesn’t show the screenshot inline and might some day go away :)
