### ISSUE TITLE
[Artist Signup CTA] Analytics QA

### ISSUE THREAD

**Issue by anipetrov** [artsy/force#773]
**New cta:**

- [x] **Experiment viewed** fires with weird variation id and name values, only in the new_cta bucket ( `new_cta?split_test[new_artist_page_cta]=new_cta?split_test[new_artist_page_cta]=new_cta`)
![image](https://cloud.githubusercontent.com/assets/8701687/22348979/ab578c1e-e3db-11e6-98f5-41efa1b1fe93.png)

- [x] Looks like **Created account** automatically picks up url params as `acquisition_initiative`. 
![image](https://cloud.githubusercontent.com/assets/8701687/22349131/5e32e93c-e3dc-11e6-9069-13b223de1d85.png)

- [x] When following an artist on payoff screen, I get a **Followed artists** event to fire (with weird properties, ed `context_module: "Homepage followed artists"`), which is not the default event for following an entity -- not sure where else we use it, but traditionally we wire up the **Followed artist** with 
  - properties: {
    entity_id: gravity id of the artist, `artist._id` in force i think  
    entity_slug: slug of the artist, `artist.id` in force i think  
    context_module: "artist page sign up prompt payoff screen"
    }

**Old cta:**

- [ ] Similarly, when you create an account from the old artist cta, I get a **Followed artists** event to fire. This time I am on the whole page, so the contextual property makes more sense (`context_module: "Homepage followed artists"`), but this is still not the default event for following an entity. We wire up the **Followed artist** with 
  - properties: {
    entity_id: gravity id of the artist, `artist._id` in force i think  
    entity_slug: slug of the artist, `artist.id` in force i think  
    context_module: "homepage follow artists"
    }

Additionally, we could instrument more *Click* events but as they will pertain differently to the different test variation, maybe we should only wire these up after we have a winner. Will lay them out in the case of new_cta below:

- [x] **Click**: When user clicks "Sign Up" button on the 
  - properties: {  
    context_module: "artist page sign up prompt"
    label: "Sign Up"
    type: "button"
    }  

- [x] **Click**: When user clicks on the "I'm done, take me back" button on the artist cta sign up payoff
  - properties: {  
    context_module: "artist page sign up prompt payoff screen"
    label: "I'm done, take me back"
    type: "button"
    }  

cc @mzikherman

**Comment by mzikherman** [comment]
> Experiment viewed fires with weird variation id and name values, only in the new_cta bucket

I can't reproduce this, are you using the query params properly? It looks like your pasted link has them duped, they should only be in the URL once. That does give me the correct output:

```
TRACKED:  Experiment Viewed {"experiment_id":"new_artist_page_cta","experiment_name":"new_artist_page_cta","variation_id":"new_cta","variation_name":"new_cta","nonInteraction":1}
```

> Looks like Created account automatically picks up url params as acquisition_initiative

Yup, that's what that code does. Remember, in the real AB test you wouldn't have any of these query params provided :)


> When following an artist on payoff screen, I get a Followed artists event to fire (with weird properties, ed context_module: "Homepage followed artists")

I can look into this, seems like a bug. Similarly for the old CTA/followed artist thing.

**Comment by anipetrov** [comment]
Thanks so much for offering to pair on this!

**Comment by mzikherman** [comment]
@anipetrov maybe let's pair again tomorrow? I'm a tad confused about the old CTA follow analytics.

That uses this old-style way of following the artist, which doesn't have any analytics firing. I think I know what to add there but I'd like to doublecheck with you first.

**Comment by anipetrov** [comment]
Sounds good Matt, thanks so much for spending the time on this!

**Comment by alloy** [comment]
Should be done, @anipetrov re-open if not the case.
