### ISSUE TITLE
Home QA

### ISSUE THREAD

**Issue by briansw** [artsy/force#78]
_From @briansw on June 10, 2016 18:18_
### Done(`homepage-qa-8`)
- [x] Add "View All" box button to end of rail
- [x] Add Save button to works by artists you follow rail
- [x] View All box button: whole area should be clickable.  on hover bg: `GRAY-LIGHTEST-COLOR` with transition
### Done(`homepage-qa-7`)
- [x] height of vertical dividers are too tall, should stop at bottom of content
- [x] small update to fair formatting https://cl.ly/3O1N2P3J2J1f
- [x] small update to auction formatting https://cl.ly/250n3I432E3t
- [x] auctioned works still say bid now after auction has passed: https://cl.ly/1V0u2F3c3v3K
- [x] Add Category header (same spec as related artist rail): http://cl.ly/2e3y2m3E3R0x
- [x] Logged out: clicking follow button doesn't pop open login/sign up modal
### Done (`homepage-qa-6`)
- [x] can continue clicking arrows even when at end or beginning which causes issues when going in other direction
### Done(`homepage-qa-5`)
- [x] grab recent 60 and shuffle, display 20
- [x] Similar to gallery rail: grab recent 60 and shuffle, display 20.
- [x] Capitalize "You" in title
- [x] Looks like we're not randomizing sequence. Should be grabbing 60 most recent and shuffling order and displaying 20
### Done(`homepage-save-button`)
- [x] Retain save functionality
### Done (`homepage-qa-3`)
- [x] Space between artwork and didactics/tombstone [whatever you prefer ;)] looks greater than normal: http://cl.ly/3E3v3u0L3X1C
- [x] Auction works are saying "Contact auction house" instead of "[Paddle] Bid now"
- [x] I've only seen recommendations once, the rest of the time the rail is empty: http://cl.ly/3u242N050w2D
- [x] Given the length of the description, let's cut it but keep the info from number of lots on down http://cl.ly/323R2J1G1w1M
- [x] Change Header prefix from "At Auction:" to "Current Auction:"
- [x] Change title to: "Current Fair: [Fair title]"
- [x] Didn't see the "new for you" bubble
### Done (`homepage-qa-2`)
- [x] Missing: "View All" cell: http://cl.ly/3g2M3w36180N
  - [x] Works by Artists You Follow
  - [x] Works from Galleries You Follow
  - [x] Recently Saved Works
  - [x] Auction rails
  - [x] Fair rails
  - [x] Artist rails
  - [x] Gene rails
- [x] Arrows should always be visible on touch devices
- [x] Make arrows visible on hover of blue zone (laura did this already on the rails for the artist page) http://cl.ly/2I2l3w26363I
- [x] Gallery/Institution line should link to gallery page
- [x] Sometimes the artwork img isnt showing up: 1) http://cl.ly/3B2d332o3q1T 2) http://cl.ly/2v3c0d2Z3z3k
  ### Done (`homepage-qa-4`)
- [x] Match spacing between border / title / content and space after: http://cl.ly/1w0i0V1E2K2Z
- [x] artwork height should be 180px
- [x] Sidebar width, margin, and vertical border to match spec: http://cl.ly/461T2f3a392R
- [x] Pagination arrows should be vertically centered on img. One exception: the follow rail (http://cl.ly/2l0n0i1o1a38)
- [x] Paginate by all works within view: http://cl.ly/0C1M3a3s2x05
- [x] When page is loading you can see the horizontal scrollbar bouncing around, would be nice to avoid on desktop, zooms the content in and out on ipad: http://cl.ly/1L253s0t3827
- [x] Is it possible to hold the placeholder gray artwork components until the works are ready to load?
- [x] Addition: Can we make the titles links. No visual distinction necessary.
  ### Done (`homepage-qa-1`)
- [x] Match spacing between border / title / content and space after: http://cl.ly/1w0i0V1E2K2Z
- [x] artwork height should be 180px
- [x] Sidebar width, margin, and vertical border to match spec: http://cl.ly/461T2f3a392R
- [x] Pagination arrows should be vertically centered on img. One exception: the follow rail (http://cl.ly/2l0n0i1o1a38)
- [x] Paginate by all works within view: http://cl.ly/0C1M3a3s2x05
- [x] When page is loading you can see the horizontal scrollbar bouncing around, would be nice to avoid on desktop, zooms the content in and out on ipad: http://cl.ly/1L253s0t3827
- [x] Is it possible to hold the placeholder gray artwork components until the works are ready to load?
- [x] Addition: Can we make the titles links. No visual distinction necessary.
##### Works by Artists You Follow
- [ ] Sidebar: when user is following 7 or less artists, search bar: http://cl.ly/1r221E2D0Y0c
- [ ] Is it possible to make the search bar same height as items? http://cl.ly/2x2K472E0d3i
##### Works from Galleries You Follow
- [ ] don't strip out autofollowed galleries
##### Fair Rail
- [x] All tier 1 fairs should show up
- [ ] Only artsy partners should be showing up here
- [x] When multiple published tier 2–5 fairs:  choose the one closing soonest
- [ ] **HOLD: fairs team might only want to display tier 1-2**
##### Related Artists
- [x] So far I've only seen one related artist based on the same followed artist. should randomly select an artist i follow and choose a related artist from there: http://cl.ly/0a323H0f232T
##### Recently Saved
- [ ] Closed auction should only have "Auction closed" note, remove "Not for sale" https://cl.ly/371s3u1Q243A

_Copied from original issue: artsy/force-private#5207_

**Comment by alloy** [comment]
Need to file tickets for the remaining TODOs.
