### ISSUE TITLE
Don’t throw 404 for just any metaphysics resolve error.

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#781]
cc @craigspaeth @joeyAghion @alloy 

Curious to your thoughts on this issue, and sorry for being long-winded!

Something that has come up several times, is how resilient Force (or specific pages) can/should be to external systems being down or out of sync. This usually manifests in server-side requests to Gravity/Metaphysics/Positron, or client-side ones, generally returning non-successful error codes and/or having promises rejected.

Client-side issues will naturally have a 'graceful' degradation when encountered, since large chunks of the page will most likely be rendered and functional anyway.

However...server-side issues are handled much less gracefully. Basically, any error in a server-side request will lead to a total 500/404 and not very nice stack/error trace, etc.

We do reject any Metaphysics promises where _any_ field had any issue resolving (https://github.com/artsy/force/blob/e3ff78ab2464ae7c83e537af15512810ab6b0c51/lib/metaphysics.coffee#L31-L34).

This could lead to one of these external systems having an issue, and an entire page failing to load. In fact we've seen that several times (+ frequently on staging).

So I'm wondering what your thoughts are on this issue. In some cases (like Gravity or Metaphysics being down), it most likely makes sense to have an error and not show anything. But, it does seem less than ideal to not load an artist or artwork page because Galaxy is down.

I'm thinking maybe we can decorate certain fields/nodes in Metaphysics (those that rely on external services) with a flag indicating their 'optional-ness', and _not_ reject the promise if any of those fields error. Then, we'd need to make any templates/calling code in Force, resilient to those fields being `null` (which is probably safe most of the time anyway, since they frequently can be `null` for valid reasons, not just having errored).

**Comment by alloy** [comment]
Correct me if I’m wrong, but doesn’t MP still send the response, albeit incomplete, and is it not _just_ Force that is deciding to throw a 404 on _any_ error? Because it seems to me that MP is behaving correct and Force should simply handle those fields that failed being `null` (which is what I _assume_ would be the case), instead of rejecting all of the data. In addition those fields should **not** be marked as `GraphQLNonNull` in MP’s schema.

**Comment by mzikherman** [comment]
Yes precisely, MP sends the response (with `null`s for error'ed fields, and a descriptive `errors` array), but Force simply rejects any promise from Metaphysics that has _anything_ returned in `errors`: handled [here](https://github.com/artsy/force/blob/e3ff78ab2464ae7c83e537af15512810ab6b0c51/lib/metaphysics.coffee#L31-L34).

So are you proposing to simply remove that `reject if errors` block in Force? I'd support that 👍

**Comment by alloy** [comment]
Yep, that’s what I’m proposing. I’m sure it was added for good reason, though, so you should do a bit of spelunking to find that reason and see if we can limit the way in which we decided to reject any response with errors.

**Comment by broskoski** [comment]
Catching up to this late. I think the only reason we decided to reject the promise if anything was present in `errors` is something like "if the presence of an error doesn't reject the promise, then what would?". But I agree, in practice it has been more of a nuisance than an aid. This recent PR / Issue is a good example: https://github.com/artsy/force/pull/796 . 

Moving towards not rejecting errors seems to make sense, it will just move the responsibility to individual requests to handle the errors, should they occur.

**Comment by alloy** [comment]
I’ve renamed this ticket to clarify what I understand to be the only work item. Please rephrase if need be.

**Comment by mzikherman** [comment]
I'm definitely down to do this.

It might be tough to see what templates/code in Force are resilient to being null (but some obvious places to check might be Galaxy returned data, on the artist page and CV).

Maybe we just remove that rejection clause, do a manual check of the Galaxy-related code and templates, and then deploy. We can then be on the lookout for any error reports.

If we want to be even 'safer', maybe we can remove the rejection clause, but replace it with a direct NewRelic ping to log `errors` so we can periodically review them.

**Comment by alloy** [comment]
> Maybe we just remove that rejection clause, do a manual check of the Galaxy-related code and templates, and then deploy. We can then be on the lookout for any error reports.

👍 

> If we want to be even 'safer', maybe we can remove the rejection clause, but replace it with a direct NewRelic ping to log `errors` so we can periodically review them.

I was under the impression that @broskoski recently added client-side error reporting, so either make sure that these errors would show up there or, if I misremembered, indeed push the error to NewRelic.

**Comment by mzikherman** [comment]
Interesting, yea I think I'll just directly ping the NewRelic API, since some of the important ones we definitely would want to track are server-side.

**Comment by alloy** [comment]
Ah good point 👍
