### ISSUE TITLE
ArtistRail

### ISSUE THREAD

**Issue by briansw** [artsy/force#79]
_From @briansw on March 29, 2016 19:42_

![artist-rail 1x](https://cloud.githubusercontent.com/assets/1022172/14121301/d7373592-f5c4-11e5-9411-4a8076dbcf89.png)
- A rail of available works by an artist the user is following
- truncate title if artist's name is too long, good artist to test: https://www.artsy.net/artist/jennifer-allora-and-guillermo-calzadilla

_Copied from original issue: artsy/force-private#4709_

**Comment by briansw** [comment]
Add the follow button here to be consistent with gene rail:

![artist-rail 1x](https://cloud.githubusercontent.com/assets/1022172/15712086/ec1e69d4-27de-11e6-923c-c4257e1b3f09.png)

**Comment by alloy** [comment]
This is done.

**Comment by briansw** [comment]
@alloy not sure how these are implemented from a technical standpoint, but just want to note that artist rails for followed artists are not currently implemented on the home page. Only related artist rails are.

**Comment by alloy** [comment]
Hmmmmm, you know what, I think this is missing on both Force and Eigen. Moving that to metaphysics https://github.com/artsy/metaphysics/issues/490. Good catch 👏
