### ISSUE TITLE
Updating artwork page for new inquireability on formerly unavailable works

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#790]
Currently, a [sold artwork](https://staging.artsy.net/artwork/jose-royo-embarcadero-1) appears:

<img width="347" alt="screen shot 2017-01-31 at 12 38 21 pm" src="https://cloud.githubusercontent.com/assets/1457859/22476933/2d03d5ea-e7b2-11e6-9d15-a7ed9c8741ba.png">

A [not for sale artwork](https://staging.artsy.net/artwork/julie-wolfe-in-a-day-flight-series-11)  appears:

<img width="318" alt="screen shot 2017-01-31 at 12 40 51 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477026/8c33cd86-e7b2-11e6-946c-4fc6ee222ff0.png">

An [on hold artwork](https://staging.artsy.net/artwork/leslie-smith-iii-prestige) appears:
<img width="326" alt="screen shot 2017-01-31 at 12 41 41 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477065/a329dd8c-e7b2-11e6-8289-5248277f5583.png">

The desired appearance: https://cloud.githubusercontent.com/assets/1022172/22441807/eb08d22c-e706-11e6-87b7-c59095118526.jpg

**Comment by mzikherman** [comment]
@tayapage6 @briansw Here are the artwork page current state on staging for the 3 statuses: not-for-sale/sold/on-hold. Can you comment on what the on-hold comp should be? Other than that it's ready to go!

**Comment by briansw** [comment]
@mzikherman I updated the design to include on hold: https://cloud.githubusercontent.com/assets/1022172/22480420/5314d768-e7bf-11e6-94ce-b53ef8992245.jpg

**Comment by mzikherman** [comment]
@briansw just for simplicity's sake, here are the 4 states and their appearance (on Microgravity and Force artwork pages):

for sale: this is unchanged, it still displays the price info/label/range, or 'Contact for Price'

sold: this now displays as 'sold' (no pricing info)

not for sale: this doesn't display anything (blank)

on hold: this displays as: "price, on hold" (if price available), otherwise just 'On hold'

For the 'on hold' state, I'd recommend a comma instead of a dash since the price could be a range (and contain a dash itself), and then lowercase 'on hold' (if no price available, 'On hold' with uppercase). This also matches the display of this state in the artwork tile view.

**Comment by mzikherman** [comment]
Closed via https://github.com/artsy/force/pull/800
