### ISSUE TITLE
Updating artwork tile/brick for new inquireability

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#791]
Currently, sold work:

<img width="288" alt="screen shot 2017-01-31 at 12 48 27 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477329/a23719fc-e7b3-11e6-8725-724397ece0c0.png">

Not for sale work:
<img width="297" alt="screen shot 2017-01-31 at 12 49 49 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477372/ce5fa152-e7b3-11e6-949b-cc529e48a04f.png">

On hold work:
<img width="301" alt="screen shot 2017-01-31 at 12 51 37 pm" src="https://cloud.githubusercontent.com/assets/1457859/22477431/0ad42752-e7b4-11e6-85ba-49ec18640390.png">

Desired: https://cloud.githubusercontent.com/assets/1022172/22441805/e90340e8-e706-11e6-8d7a-a5e8e4753d08.jpg

**Comment by briansw** [comment]
![screen shot 2017-01-31 at 4 55 02 pm](https://cloud.githubusercontent.com/assets/1022172/22486071/088b5728-e7d6-11e6-9742-5f04390baa47.png)

**Comment by mzikherman** [comment]
@briansw this is consistent with the artwork page views for Microgravity and Force (yay!), except for one thing- the 'sold' label is treated like 'not for sale' (ie- totally hidden), whereas the artwork page updates still include it saying 'Sold'.

Is this intentional? Should this (or the artwork page) have the 'sold' treatment adjusted to match?

**Comment by broskoski** [comment]
Closed in https://github.com/artsy/metaphysics/pull/538
