### ISSUE TITLE
sometimes login/signup redirects you to the wrong page afterwards

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/force#793]
this has been reported by several people, also happens in microgravity. needs to be investigated, might be an artsy passport problem.

**Comment by 1aurabrown** [comment]
see also https://github.com/artsy/microgravity/issues/110

**Comment by tayapage6** [comment]
Needs repo case

**Comment by craigspaeth** [comment]
@broskoski @1aurabrown I've got a theory about this logged here https://github.com/artsy/artsy-passport/issues/101

**Comment by alloy** [comment]
@1aurabrown Can you see if you can make the required fix in passport?

**Comment by 1aurabrown** [comment]
i still haven't been able to repro this, but it seems that it could sometimes happen as the result of the issue craig mentioned. https://github.com/artsy/artsy-passport/pull/102 should fix

**Comment by alloy** [comment]
Seems good 👍
