### ISSUE TITLE
A/B Test: Forced Signups to inquire

### ISSUE THREAD

**Issue by briansw** [artsy/force#80]
_From @briansw on July 26, 2016 19:31_

#### About the test
Users are currently able to submit inquiries to galleries without creating an account. We'd like to test how sharp of a decline we'll see by forcing users to sign up to inquire as well as to determine if the quality of inquiries rise.

#### Notes
- Release as internal lab feature prior to A/B test to ensure all flows and analytics are firing properly
- A/B test should be 50/50 split with all admins in test group
- Preserve existing code in case we need to revert back to current inquiry flow
- Prototype for transitions: http://files.artsy.net/other/inquire-3.zip
- Ensure we are following the artist the user is inquiring on at the time of account creation

#### Flows to address
- [x] Artwork inquiry
- [x] Artwork pre-qualification inquiry
- [x] Partner contact from:
  - [x] /shows
   - [x] /[fair] and /[fair]/browse/booths

![inquire](https://cloud.githubusercontent.com/assets/1022172/17444931/9e4385a4-5b10-11e6-8fe4-e745f899b27d.jpg)

---

#### Card adjustments
![cards](https://cloud.githubusercontent.com/assets/1022172/18449289/a323702a-78fc-11e6-8337-eb8fd1e82a7c.jpg)

_Copied from original issue: artsy/force-private#5412_

**Comment by broskoski** [comment]
How do we feel about keeping the minor changes (things like non-fullscreen feedback, following artist, style adjustments and transitions) out of this test and for future revisions? IMHO if we want this to be a true test of judging between non-logged-in inquiries and logged in, we should scope the changes to only the flow and nothing else. 

cc @briansw @robertlenne

**Comment by briansw** [comment]
The style adjustment (header of card) and animation (the slideup of the signup card over the inquiry message) were introduced to ensure there's no confusion around whether or not the user's inquiry has been sent. My vote would be to keep all of this as spec'd as I think it could negatively impact the test results.

Placing the "your message has been sent" notification in the white box and the horizontal transitions during the questionnaire are less important and could be skipped for now.

@robertlenne @katarinabatina curious what your thoughts are.
