### ISSUE TITLE
Need better error reporting in inquiry flow / Spike in "Problem sending inquiry" emails 

### ISSUE THREAD

**Issue by broskoski** [artsy/force#801]
Reports came in early Feb 1, that a partner "registered interest through her personal email and was able to log an inquiry with some artists but not all". @joeyAghion noted that there has been a recent spike in "Problem sending inquiry emails" (these emails get sent when the inquiry flow errors out at any point).

Trying to replicate an error with the same artwork on staging (with both new and old accounts) did not result in an error, which limits our ability to troubleshoot this issue. First step here is to revisit how we deal with client-side error reporting.

**Comment by 1aurabrown** [comment]
Is it originating from here? if so we can get more out of the context
https://github.com/artsy/force/blob/master/analytics/inquiry_questionnaire.js#L137

**Comment by alloy** [comment]
Did done
