### ISSUE TITLE
[Artwork] Add line for ‘Not for Sale’

### ISSUE THREAD

**Issue by mzikherman** [artsy/force#810]
And add in the grey line on the artwork page for 'Not for sale'

**Comment by alloy** [comment]
Only still needs the line done.

**Comment by 1aurabrown** [comment]
@mzikherman @alloy I can do this if somebody tells me where the "gray line" is supposed to be

**Comment by alloy** [comment]
@mzikherman @tayapage6 Can either of you include the info @1aurabrown requested? I’m also unsure.
