### ISSUE TITLE
Artwork favorites 3rd column dropping below first

### ISSUE THREAD

**Issue by briansw** [artsy/force#823]
Looks like there are a couple browser widths where it works correctly, but otherwise the third column is getting kicked below the first:

![screen shot 2017-02-07 at 10 02 04 am](https://cloud.githubusercontent.com/assets/1022172/22696592/92cc1a9e-ed1c-11e6-9f9a-2c42ff9fee04.png)

**Comment by madeleineb** [comment]
I could swear I've seen this before on gene pages when looking at the artwork view, but I'm currently unable to replicate. So far as I know, at the moment this is just localized.

**Comment by 1aurabrown** [comment]
this is an easy fix on this saved works page, but it could still exist elsewhere for different reasons. let me know if it comes up on other pages!
