### ISSUE TITLE
Artwork page: Ribbon pushes form off page

### ISSUE THREAD

**Issue by briansw** [artsy/force#831]
![screen recording 2017-02-08 at 02 18 pm](https://cloud.githubusercontent.com/assets/1022172/22753307/ae6a2686-ee09-11e6-8af1-7d5acb613f4b.gif)

**Comment by 1aurabrown** [comment]
@briansw What browser were you using when you saw this? I haven't ben able to reproduce in Safari or Chrome. Had you done anything else besides just loading the page?

**Comment by briansw** [comment]
Chrome. Just loaded the page was happening consistently when I posted looks like it doesn't do it anymore...

**Comment by joeyAghion** [comment]
From an incognito window, I can repro this on practically any artwork:

https://www.artsy.net/artwork/volodymyr-zayichenko-17022017-kn6b-1234a-london-uk
https://www.artsy.net/artwork/volodymyr-zayichenko-spark
https://www.artsy.net/artwork/lajos-tscheligi-abstract-thinking

**Comment by 1aurabrown** [comment]
hmm @joeyAghion i still can't repro:
![screen shot 2017-02-24 at 2 29 17 pm](https://cloud.githubusercontent.com/assets/3171662/23305161/c2449bd2-fa9d-11e6-983c-62c06d799fcc.png)

**Comment by alloy** [comment]
@tayapage6 Add notes about repro.

**Comment by joeyAghion** [comment]
@l2succes I can still repro this at the URLs listed above. I suspect it has something to do with the purchase request A/B test, since @1aurabrown's screenshot shows a "purchase" button while I see "contact gallery."

**Comment by mzikherman** [comment]
Repro in Chrome: https://www.artsy.net/artwork/andy-warhol-skull?split_test[purchase_flow]=default  (force being in the control group for purchase AB test).
