### ISSUE TITLE
Auction timer missing from artwork pages

### ISSUE THREAD

**Issue by briansw** [artsy/force#834]
Previously it showed up here: 
![screen shot 2017-02-09 at 11 04 19 am](https://cloud.githubusercontent.com/assets/1022172/22791496/8cbac776-eeb7-11e6-8dbc-9e38c7fe3c39.png)

cc @katarinabatina

**Comment by sweir27** [comment]
I'm not sure if this is a bug. We intentionally removed the "Bidding Closes" timer for auctions that are live (if they haven't opened for live bidding yet, it should say "Live Bidding Opens In..."). For these auctions we have no knowledge of when they end, so we can't have a timer once they are open for live bidding.

**Comment by katarinabatina** [comment]
@sweir27 can we bring the timer back and just change the language then?

**Comment by sweir27** [comment]
What should the time be then? Like "Live Auction Open For ..."? We just don't have end times so there won't be a countdown to anything.

**Comment by sweir27** [comment]
It looks like it may be broken in the before-live-opens state, so we should make sure to fix it there, just not sure what to do in the other case

**Comment by katarinabatina** [comment]
@sweir27 for when the live auction opens, I agree, we should get rid of the timer and instead change the EXPLORE AUCTION button, to JOIN LIVE AUCTION.
