### ISSUE TITLE
Better handling of ambiguous city names

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#860]
### Problem

Currently in the locations dropdown on /galleries, we don't disambiguate between cities that happen to have the same name.

This is an example of a legit duplicate name, representing **Naples, Florida** and **Naples, Italy** both of which contain partners:

![naples](https://cloud.githubusercontent.com/assets/140521/22950861/06832c94-f2d5-11e6-8180-3cf794b9d40b.png)

Also — due to messy data entry issues we may end up with spurious duplicates such as **Paris, Texas** and **Paris, France** (only the latter has partners):

![paris](https://cloud.githubusercontent.com/assets/140521/22951088/e1ab0e54-f2d5-11e6-946d-b855fd42a244.png)

The latter case is kind of a different problem, but in either case it is confusing to not know which menu item corresponds with which city.

### Solutions? 

A simple solution would be to fully qualify all these names:

![fully](https://cloud.githubusercontent.com/assets/140521/22952002/52757b26-f2d9-11e6-9f27-6a1dc6603f49.png)

Or at the risk of being US-centric, we could lose the trailing "USA":

![abbrev](https://cloud.githubusercontent.com/assets/140521/22952044/705ec5de-f2d9-11e6-8aed-2a3f6a4ee77f.png)

A side effect is that the featured cities that appear by default before you start the type-ahead behavior would also get the longer names, which may or may not be desirable? 

![featured](https://cloud.githubusercontent.com/assets/140521/22952166/e20acb4c-f2d9-11e6-937f-208cccd4f87a.png)

Curious to know your thoughts @brentcas @jordanchart

**Comment by jordanchart** [comment]
To your last point, I do think it looks better when there is no state/country listed after the name of the city. That said, we do want to be able to differentiate between Naples FL and Naples Italy... 

I notice that one of the 'Hamilton' entires is for Bermuda, but there are no galleries on this page: https://www.artsy.net/galleries?location=hamilton-bermuda. 

How did you pull the list you sent me of duplicate cities? Would love to go through in greater detail to see how many of the duplicates are legit or if any are like the "London" entry we fixed.

**Comment by brentcas** [comment]
Hey I met with the design team and the solution we landed on was:

- Have full set of information
- Format states in the US as acronyms - 'MI' instead of 'Michigan'
- Format countries with their full name - 'United Kingdom' instead of 'UK'
- All text after the city name should be hex 999999 (this should be the color variable `gray-dark-color`)
- Bonus points: On hover, the city text should turn purple

So it would end up looking like this:

![searching v2](https://cloud.githubusercontent.com/assets/2916561/22989158/c738795a-f382-11e6-9e27-e339e12ae534.png)

**Comment by jordanchart** [comment]
I think that looks great!

**Comment by anandaroop** [comment]
Thanks @brentcas ! Lemme take a closer look and see what would be involved to implement this.

**Comment by anandaroop** [comment]
@jordanchart the list of locations I gave you the other day came from a console query, let me see about running it for the broader list of duplicate cities. Thanks!

**Comment by anandaroop** [comment]
@jordanchart here's a full report of [all PartnerLocations that appear in duplicated city names](https://docs.google.com/a/artsymail.com/spreadsheets/d/1xM1eobh7FfSsmzd9aG9cU-4GQguce8E2DX98C-NTy6g/edit?usp=sharing).

The good new is that out of ~100 locations there's really only 1 suspicious one, highlighted in red. I think if we fix that, we won't have any more spurious duplicates. 

The remaining duplicates appear to be legit and will have to be handled through design, as spec'd above.
