### ISSUE TITLE
Some images not showing up (due to zero height)

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#870]
Reported on Slack: https://artsy.slack.com/archives/partner-s-help/p1487119184004472

Some images in [this partner show](https://www.artsy.net/show/louis-stern-fine-arts-elizabeth-patterson-paris-and-other-places) are not being rendered in the artwork grid layout:

![nan](https://cloud.githubusercontent.com/assets/140521/22991781/78ead424-f38b-11e6-9700-8eacde616f46.png)

It appears that there is [a ViewHelper which tries to calculate](https://github.com/artsy/force/blob/dacb41a7c51bc2085b97150b811bb17e7e01970c/apps/show/helpers/view_helpers.coffee#L25-L29) some optimal layout settings based on an image's `width` and `height` as returned by Metaphysics

BUT… sometimes Metaphysics doesn't return the height/width metadata for an image, as shown by these console.logs (note the `nulls`)… which results in a div by zero / NaN value being passed to the template.

```
2:23:18 PM web.1 |  { url: 'https://d32dm0rphc51dk.cloudfront.net/DwdY0-ehhWXGL-9-yTospw/large.jpg',
2:23:18 PM web.1 |    width: 3960,
2:23:18 PM web.1 |    height: 5026 }
2:23:18 PM web.1 |  { url: 'https://d32dm0rphc51dk.cloudfront.net/ysM4y7vfaPDBzQpitRJR0Q/large.jpg',
2:23:18 PM web.1 |    width: null,
2:23:18 PM web.1 |    height: null }
2:23:18 PM web.1 |  { url: 'https://d32dm0rphc51dk.cloudfront.net/cG-FFMpEWY9wbnH5cE7BvA/large.jpg',
2:23:18 PM web.1 |    width: null,
2:23:18 PM web.1 |    height: null }
2:23:18 PM web.1 |  { url: 'https://d32dm0rphc51dk.cloudfront.net/J_NOHi4zf-_4jxyd1zVzGw/large.jpg',
2:23:18 PM web.1 |    width: 900,
2:23:18 PM web.1 |    height: 428 }
```

**Comment by anandaroop** [comment]
After some discussion with @mzikherman it looks like the step on Gemini where geometry should be returned for an image is never reached bc of an EXIF-related error on [the step preceding it](https://github.com/artsy/gemini/blob/f4d1e14f2053fab585e0bc47f3b59639045774e1/app/util/image_geometry.rb#L62).

I asked the liaison for an example of a failing and a succeeding image, and there was an obvious difference in associated EXIF and IPTC metadata.

So I used [exiv2](http://www.exiv2.org/getting-started.html) to strip all metadata from one of the failing images…

```sh
exiv2 rm ruedesaintperes.jpeg
```
…and asked her to re-upload and this time it worked 🎉

**Comment by anandaroop** [comment]
I also checked to see which if any client apps care about EXIF data and it seems like [basically none](https://github.com/search?q=org%3Aartsy+exif&type=Code).

Perhaps we could remove the EXIF check altogether. I can open in issue over Gemini if you think that's a good idea @mzikherman ?

**Comment by mzikherman** [comment]
Yup, we can probably remove/rescue from it: https://github.com/artsy/gemini/issues/231

**Comment by alloy** [comment]
@roop Will you be deploying the Gemini changes and re-populate the works that are missing dimensions data?

**Comment by anandaroop** [comment]
Yep, I will be following up on the deploy and migration today.

**Comment by anandaroop** [comment]
Resolved via [this migration](https://github.com/artsy/gemini/issues/231#issuecomment-282751930)
