### ISSUE TITLE
Create Writer channel: "Institutional Partner Updates"

### ISSUE THREAD

**Issue by remyferber** [artsy/force#873]
The existing Writer channel, Artsy Partner Updates, was originally intended to include both gallery and institutional updates (before the blog design overhaul and before CMS for Institutions shipped, so it was relevant to group everything together since the product was the same). 

Following these design and product changes and anticipating an overhaul of Artsy Partner Updates to include content exclusively for Gallery partners, we need a separate channel for Institutions. It doesn't need to be navigable on Artsy, just need a dedicated channel where we can publish content to share with partners via email & support. Distinguishing content between galleries and institutions is important not only because of differing product features, but also because the messaging varies drastically. 

The new Writer channel should be called "Institutional Partner Updates" and I can provide any relevant metadata for that process. As a final step, we'll need to change the database name of "Artsy Partner Updates"

**Comment by kanaabe** [comment]
@remyferber what should Artsy Partner Updates be renamed to?

**Comment by kanaabe** [comment]
Guessing it's "Gallery Partner Updates" 😄

**Comment by starsirius** [comment]
@remyferber When we have separate channels for gallery and institution updates, do we want to do corresponding CMS changes, e.g. gallery partners see gallery updates and institutions see their own?

**Comment by remyferber** [comment]
yes! we have separate channels now so would be great to pair with
corresponding CMS. that was next on my list to ask :)
