### ISSUE TITLE
switch to yarn from npm shrinkwrap

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/force#877]
I started taking a look at this, but the versions of dependencies installed by these two different methods differ slightly, and I was getting a lot of errors for missing methods on trying to build the app locally. I think this just takes some time to go through and examine which of these discrepancies cause breaking changes, and perhaps writing a more explicit package.json to make sure that compatible versions of dependencies are installed. in theory this shouldn't be happening since we typically specify that we would like to install a version compatible with the version specified, but it's hard to rely on every open source author to respect semantic versioning perfectly.

**Comment by craigspaeth** [comment]
Closing as we're now on Yarn with the merged codebase.

**Comment by 1aurabrown** [comment]
:]
