### ISSUE TITLE
Add See All buttons to Galleries and Institutions lists in the sidebar

### ISSUE THREAD

**Issue by briansw** [artsy/force#88]
Right now we limit the total number of displayable galleries and institutions to 10. Instead, we should allow users to see all galleries and institutions associated with the artist.

- [x] Initial limit should be 5
- [x] Don't display "See All" when 5 or fewer items in the list
- [x] Order list by number of works (desc) followed by alpha order

![galleries-institutions](https://cloud.githubusercontent.com/assets/1022172/17977946/ae6d6da8-6ac1-11e6-8ff1-d9f931ee6917.jpg)

See http://artsy.net/collect for functionality.

**Comment by 1aurabrown** [comment]
cc @mzikherman
