### ISSUE TITLE
Update cookie session config to be compatible with API

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force#906]
Looks like we're using old options which is fine that it's been going to defaults, but we need to change the session key now that the merged codebase has breaking changes to the session.

See new API https://github.com/expressjs/cookie-session

And notice us using `key` and such here https://github.com/artsy/force/blob/master/mobile/lib/setup.coffee#L78 and here https://github.com/artsy/force/blob/master/desktop/lib/setup.coffee#L138

**Comment by 1aurabrown** [comment]
@craigspaeth do we need to change the key itself, or just change `key` to `keys` and put the key in an array?

**Comment by craigspaeth** [comment]
Looks like `key` and `keys` mean new things now, but looks like we could still use `secret` but have to migrate the other settings...

`key` -> `name`
`secureProxy` -> `secure`

**Comment by alloy** [comment]
Fixed by #908.
