### ISSUE TITLE
/galleries primary carousel occasionally appears empty

### ISSUE THREAD

**Issue by anandaroop** [artsy/force#95]
Currently the primary carousel on /galleries appears empty for a couple of our cities, creating an awkward blank space between the filters and the rails below.

Normally [the criteria for selecting carousel shows](https://github.com/artsy/force/blob/master/apps/galleries_institutions/components/primary_carousel/fetch.coffee#L26) for featured cities yields at least one result, but that is not the case right now for Miami and Milan

Perhaps we are seeing this only now bc of the low number of [`current_displayable_shows`](https://github.com/artsy/gravity/blob/master/app/models/util/subscription_rule_ui_helper.rb#L14) in August.

We could either hide the carousel if it's empty, or have fallback criteria to ensure that is populated with >0 shows.

![gpc](https://cloud.githubusercontent.com/assets/140521/18018231/bf2c0d42-6ba3-11e6-81ee-1041a95a6c30.gif)

**Comment by tayapage6** [comment]
For now, the quick solution of just hiding the blank space is fine
