### ISSUE TITLE
forgot password modal can't be closed

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#966]
After submitting the forgot-password form, I see this confirmation within the modal:

![](https://cl.ly/3e0b1Y1e452e/Screen%20Shot%202017-03-03%20at%204.37.20%20PM.png)

Clicking on the ✖️ or outside the modal both fail to close the modal.

**Comment by mzikherman** [comment]
Closed via https://github.com/artsy/force/pull/1338
