### ISSUE TITLE
Sign up and get redirected home sometimes

### ISSUE THREAD

**Issue by craigspaeth** [artsy/force#978]
- [x] Newly favorited works come in order of favoritig
- [ ] Sign up and get redirected home sometimes
- [x] Can we save notes to user model easily? Otherwise just comment out the anything else.
- [x] Slow down thank you flash message

Nice to have:
- [ ] Microinteraction on favorites
- [ ] Price numbers follow knobules of slider
- [ ] Some kind of dancing wizard at the end (jk but not really)

**Comment by alloy** [comment]
The redirect _might_ be because of personalise.
