### ISSUE TITLE
Tooltip z-index is off and getting cropped

### ISSUE THREAD

**Issue by briansw** [artsy/force#979]
![screen recording 2017-03-07 at 03 55 pm](https://cloud.githubusercontent.com/assets/1022172/23678049/7aec34fa-0350-11e7-8c4f-bd9e0cfe5675.gif)

#### z-index lower than slideshow arrows
![pasted_image_at_2017_03_07_03_51_pm_720](https://cloud.githubusercontent.com/assets/1022172/23678028/6bdbb7c4-0350-11e7-8682-77437a1af55c.png)

**Comment by mzikherman** [comment]
@briansw I can't repro, and this looks to have been fixed? Feel free to re-open otherwise.
