### ISSUE TITLE
Recover from failed or slow secondary requests

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#986]
This came up specifically in the context of the home page error-ing with `503` when Positron requests were timing out (after 5 seconds). This maybe isn't a big production risk since 5 seconds is already pretty generous, but could be a simple opportunity for more graceful degradation. When article requests fail or time-out, Force could render a home page without magazine content.

The page would only be slightly leaner, and a temporarily bad situation in 1 system would be prevented from cascading across others. It's also a nice practice for our increasingly complex ecosystem in general... we could put small services into maintenance mode briefly without needing to coordinate down time all over the product.

**Comment by kanaabe** [comment]
10/31 - Positron staging down, suffering from ^
