### ISSUE TITLE
Iconfont not loading

### ISSUE THREAD

**Issue by dzucconi** [artsy/force#994]
![](http://static.damonzucconi.com/_capture/GYmmZCaWA2.png)

![](http://static.damonzucconi.com/_capture/c8uOmmyjUX.png)

**Comment by mzikherman** [comment]
👋

**Comment by dzucconi** [comment]
👋

**Comment by alloy** [comment]
:wave:

**Comment by broskoski** [comment]
Hi @dzucconi, thanks for submitting this issue. Just a few questions before I get started here, what browser are you using in this screenshot, and is the problem consistent (and is it still happening for you)?

Thanks again for submitting this issue, we really really appreciate it.

Best wishes,
cab

**Comment by dzucconi** [comment]
I noticed this for a few days then just `shift+cmd+r` refreshed and it's gone now. So — *Great job everyone*.

**Comment by alloy** [comment]
We waved it away!
